/**
 * @generated from shared-assets/vitepress-template/config.mts.tpl
 * DO NOT EDIT THIS FILE DIRECTLY — edit the template and re-run render-config.py
 *
 * 模板变量（render-config.py 替换）：
 *   java         e.g. "ai", "java", "clickhouse"
 *   /java/       e.g. "/ai/", "/clickhouse/"
 *   Java Web Dev Manual      e.g. "AI 工程全栈"
 *   Java Web 开发手册 - 开发流程 · 实现思路 · 重点关注 · 技术栈       e.g. "系统化学习 AI 工具..."
 *   #8b5cf6     e.g. "#8b5cf6"
 *   zh-CN       e.g. "zh-CN"
 *   基于 VitePress 构建 · Java Web 开发系统化手册 · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>  e.g. "AI 工程全栈 - 工具 / 大模型 / SDK / Agent"
 *   [
      { icon: 'github', link: 'https://github.com' }
    ]   e.g. '[{ icon: "github", link: "https://github.com" }]'
 */
import { defineConfig } from 'vitepress'
import { fileURLToPath, URL } from 'node:url'

// P0: VitePress/rollup 默认 fs.allow 限制 cwd 外 import。用 vite alias 解决相对路径。
const SHARED_ASSETS = fileURLToPath(new URL('../../shared-assets', import.meta.url))

export default defineConfig({
  vite: {
    resolve: {
      alias: [
        { find: '@shared', replacement: SHARED_ASSETS },
      ],
    },
  },
  base: '/java/',
  title: 'Java Web Dev Manual',
  description: 'Java Web 开发手册 - 开发流程 · 实现思路 · 重点关注 · 技术栈',
  lang: 'zh-CN',
  lastUpdated: true,
  srcDir: 'docs',
  cleanUrls: true,
  ignoreDeadLinks: true,
  head: [
    ['meta', { name: 'viewport', content: 'width=device-width,initial-scale=1,viewport-fit=cover' }],
    ['meta', { name: 'theme-color', content: '#8b5cf6' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:locale', content: 'zh_CN' }],
    ['meta', { property: 'og:site_name', content: 'Java Web Dev Manual' }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['link', { rel: 'icon', href: '/favicon.svg', type: 'image/svg+xml' }],
    ['link', { rel: 'icon', href: '/favicon.ico', type: 'image/x-icon' }],
    ['link', { rel: 'apple-touch-icon', href: '/apple-touch-icon.png', sizes: '180x180' }],
  ],
  themeConfig: {
    siteTitle: 'Java Web Dev Manual',

    // === 统一 nav（C1 规范：顶部 7 项 + 跨站 dropdown）===
    // 1) 门户  2) 首页  3) 知识图谱  4) 思维导图  5) 命令速查  6) 学习路径  7) 更多站点 ▼
    nav: [
      { text: '🏠 门户', link: 'https://java-px.bot.cd/', target: '_blank' },
      { text: '首页', link: '/' },
      { text: '知识图谱', link: '/graph' },
      { text: '思维导图', link: '/mindmap' },
      { text: '命令速查', link: '/cheatsheet' },
      { text: '学习路径', link: '/path' },
      {
        text: '更多站点',
        items: [
                  { text: "ElasticSearch", link: "https://java-px.bot.cd/es/" },
        { text: "MySQL", link: "https://java-px.bot.cd/mysql/" },
        { text: "Redis", link: "https://java-px.bot.cd/redis/" },
        { text: "微服务 / Spring Cloud", link: "https://java-px.bot.cd/cloud/" },
        { text: "Python", link: "https://java-px.bot.cd/python/" },
        { text: "Kafka", link: "https://java-px.bot.cd/kafka/" },
        { text: "在线工具", link: "https://java-px.bot.cd/tools/" },
        { text: "前端 & Node", link: "https://java-px.bot.cd/frontend/" },
        { text: "Linux 服务器", link: "https://java-px.bot.cd/linux/" },
        { text: "云原生 / Docker / K8s", link: "https://java-px.bot.cd/cloud-native/" },
        { text: "AI 工具 / 大模型", link: "https://java-px.bot.cd/ai/" },
        { text: "大数据", link: "https://java-px.bot.cd/bigdata/" },
        { text: "计算机网络", link: "https://java-px.bot.cd/network/" },
        { text: "视频处理", link: "https://java-px.bot.cd/video/" },
        { text: "文件系统与存储", link: "https://java-px.bot.cd/filesystem/" },
        { text: "Java 语言", link: "https://java-px.bot.cd/java-language/" },
        { text: "企业级架构", link: "https://java-px.bot.cd/architecture/" },
        { text: "系统设计", link: "https://java-px.bot.cd/system-design/" },
        { text: "PostgreSQL", link: "https://java-px.bot.cd/postgresql/" },
        { text: "可观测性", link: "https://java-px.bot.cd/observability/" },
        { text: "安全", link: "https://java-px.bot.cd/security/" },
        { text: "DevOps", link: "https://java-px.bot.cd/devops/" },
        { text: "Rust", link: "https://java-px.bot.cd/rust/" },
        { text: "Go", link: "https://java-px.bot.cd/go/" },
        { text: "ClickHouse", link: "https://java-px.bot.cd/clickhouse/" },
        { text: "设计模式", link: "https://java-px.bot.cd/design-pattern/" },
        { text: "混沌工程", link: "https://java-px.bot.cd/chaos/" },
        { text: "物联网", link: "https://java-px.bot.cd/iot/" },
        { text: "安卓", link: "https://java-px.bot.cd/android/" },
        { text: "游戏开发", link: "https://java-px.bot.cd/game/" },
        ]
      }
    ],

    // === 各站独立 sidebar（render-config.py 保留原值）===
    sidebar: {
    
        
            
                
                                      '/01-process/': [
                                        {
                                          text: '开发流程',
                                          items: [
                                            { text: '总览', link: '/01-process/overview' },
                                            { text: '需求分析', link: '/01-process/requirement-analysis' },
                                            { text: '技术方案', link: '/01-process/tech-solution' },
                                            { text: '数据库设计', link: '/01-process/database-design' },
                                            { text: '接口设计', link: '/01-process/api-design' },
                                            { text: '编码开发', link: '/01-process/coding' },
                                            { text: '代码评审', link: '/01-process/code-review' },
                                            { text: '单元测试', link: '/01-process/unit-test' },
                                            { text: '集成测试', link: '/01-process/integration-test' },
                                            { text: '部署上线', link: '/01-process/deployment' },
                                            { text: '监控运维', link: '/01-process/monitoring' },
                                            { text: '迭代优化', link: '/01-process/iteration' },
                                            { text: '文档沉淀', link: '/01-process/documentation' }
                                          ]
                                        }
                                      ],
                                      '/02-design/': [
                                        {
                                          text: '实现思路',
                                          items: [
                                            { text: '总览', link: '/02-design/overview' },
                                            { text: '分层架构', link: '/02-design/layered-architecture' },
                                            { text: 'MVC 模式', link: '/02-design/mvc-pattern' },
                                            { text: '依赖注入', link: '/02-design/dependency-injection' },
                                            { text: 'AOP 切面', link: '/02-design/aop' },
                                            { text: 'RESTful 风格', link: '/02-design/restful-api' },
                                            { text: '领域驱动 DDD', link: '/02-design/ddd' },
                                            { text: '微服务架构', link: '/02-design/microservices' },
                                            { text: '责任链模式', link: '/02-design/chain-of-responsibility' },
                                            { text: '策略模式', link: '/02-design/strategy-pattern' },
                                            { text: '模板方法模式', link: '/02-design/template-method' },
                                            { text: '工厂模式', link: '/02-design/factory-pattern' },
                                            { text: '代理模式', link: '/02-design/proxy-pattern' }
                                          ]
                                        }
                                      ],
                                      '/03-practice/': [
                                        {
                                          text: '重点关注',
                                          items: [
                                            { text: '总览', link: '/03-practice/overview' },
                                            { text: '异常处理', link: '/03-practice/exception-handling' },
                                            { text: '日志规范', link: '/03-practice/logging' },
                                            { text: '参数校验', link: '/03-practice/validation' },
                                            { text: '事务管理', link: '/03-practice/transaction' },
                                            { text: '缓存策略', link: '/03-practice/cache-strategy' },
                                            { text: '安全实践', link: '/03-practice/security' },
                                            { text: '性能优化', link: '/03-practice/performance' },
                                            { text: '代码规范', link: '/03-practice/code-style' },
                                            { text: '接口幂等', link: '/03-practice/idempotency' },
                                            { text: '数据脱敏', link: '/03-practice/data-masking' },
                                            { text: '限流熔断', link: '/03-practice/rate-limiting' },
                                            { text: '并发控制', link: '/03-practice/concurrency' }
                                          ]
                                        }
                                      ],
                                      '/04-tech/': [
                                        {
                                          text: '技术栈',
                                          items: [
                                            { text: '总览', link: '/04-tech/overview' },
                                            { text: 'Spring Boot', link: '/04-tech/spring-boot' },
                                            { text: 'Spring MVC', link: '/04-tech/spring-mvc' },
                                            { text: 'Spring Security', link: '/04-tech/spring-security' },
                                            { text: 'MyBatis / Plus', link: '/04-tech/mybatis' },
                                            { text: 'MySQL', link: '/04-tech/mysql' },
                                            { text: 'Redis', link: '/04-tech/redis' },
                                            { text: '消息队列 MQ', link: '/04-tech/message-queue' },
                                            { text: 'Maven / Gradle', link: '/04-tech/build-tools' },
                                            { text: 'Docker', link: '/04-tech/docker' },
                                            { text: 'Nginx', link: '/04-tech/nginx' },
                                            { text: '测试框架', link: '/04-tech/testing' },
                                            { text: '接口文档', link: '/04-tech/api-doc' }
                                          ]
                                        }
                                      ]
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com' }
    ],

    outline: { level: [2, 3], label: '页面大纲' },
    docFooter: { prev: '上一篇', next: '下一篇' },
    search: { provider: 'local' },

    footer: {
      message: '基于 VitePress 构建 · Java Web 开发系统化手册 · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>',
      copyright: 'MIT License'
    },
  }
})
