/**
 * @generated from shared-assets/vitepress-template/config.mts.tpl
 * DO NOT EDIT THIS FILE DIRECTLY — edit the template and re-run render-config.py
 *
 * 模板变量（render-config.py 替换）：
 *   design-pattern         e.g. "ai", "java", "clickhouse"
 *   /design-pattern/       e.g. "/ai/", "/clickhouse/"
 *   设计模式      e.g. "AI 工程全栈"
 *   GoF 23 模式 + 现代架构模式 + 反模式自查表 - 创建型 / 结构型 / 行为型 · 依赖注入 · CQRS · Event Sourcing · Saga · 6 大类 · 36 节点 · Java + Go + TypeScript 多语言实现       e.g. "系统化学习 AI 工具..."
 *   #7c3aed     e.g. "#8b5cf6"
 *   zh-CN       e.g. "zh-CN"
 *   设计模式是面向对象编程与软件工程的核心抽象武器 · <a href="https://en.wikipedia.org/wiki/Design_Patterns" target="_blank">GoF 1994</a> · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>  e.g. "AI 工程全栈 - 工具 / 大模型 / SDK / Agent"
 *   []   e.g. '[{ icon: "github", link: "https://github.com" }]'
 */
import { defineConfig } from 'vitepress'
import { withMermaid } from 'vitepress-plugin-mermaid'
import { fileURLToPath, URL } from 'node:url'

// P0: VitePress/rollup 默认 fs.allow 限制 cwd 外 import。用 vite alias 解决相对路径。
const SHARED_ASSETS = fileURLToPath(new URL('../../shared-assets', import.meta.url))

// C11: Mermaid 跨站共享配置（inline 而非 import，避免 vite alias 在 Node 加载 config.mts 阶段不生效的问题）
// 同步源：shared-assets/mermaid-config/base.ts（修改时请同步更新此处）
// 见 §8.46
const mermaidBase = {
  securityLevel: 'loose',
  startOnLoad: false,
  theme: 'base',
  fontFamily: '"Inter", "PingFang SC", "Microsoft YaHei", system-ui, -apple-system, sans-serif',
} as const

function lightenHex(hex: string, ratio: number): string {
  const m = hex.replace('#', '').match(/^([0-9a-f]{6})$/i)
  if (!m) return hex
  const r = parseInt(m[1].slice(0, 2), 16)
  const g = parseInt(m[1].slice(2, 4), 16)
  const b = parseInt(m[1].slice(4, 6), 16)
  const mix = (c: number) => Math.round(c + (255 - c) * ratio)
  return '#' + [mix(r), mix(g), mix(b)].map(c => c.toString(16).padStart(2, '0')).join('')
}

function mermaidTheme(brand: string) {
  const soft = lightenHex(brand, 0.85)
  const ink = '#1f2937'
  const line = '#94a3b8'
  return {
    primaryColor: brand,
    primaryTextColor: ink,
    primaryBorderColor: brand,
    lineColor: line,
    secondaryColor: soft,
    tertiaryColor: '#fafafa',
    fontFamily: mermaidBase.fontFamily,
    fontSize: '14px',
  }
}

export default withMermaid( defineConfig({
  vite: {
    resolve: {
      alias: [
        { find: '@shared', replacement: SHARED_ASSETS },
      ],
    },
  },
    mermaid: {
    ...mermaidBase,
    themeVariables: mermaidTheme('#7c3aed'),
  },
    base: '/design-pattern/',
  title: '设计模式',
  description: 'GoF 23 模式 + 现代架构模式 + 反模式自查表 - 创建型 / 结构型 / 行为型 · 依赖注入 · CQRS · Event Sourcing · Saga · 6 大类 · 36 节点 · Java + Go + TypeScript 多语言实现',
  lang: 'zh-CN',
  lastUpdated: true,
  srcDir: 'docs',
  cleanUrls: true,
  ignoreDeadLinks: true,
  head: [
    ['meta', { name: 'viewport', content: 'width=device-width,initial-scale=1,viewport-fit=cover' }],
    ['meta', { name: 'theme-color', content: '#7c3aed' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:locale', content: 'zh_CN' }],
    ['meta', { property: 'og:site_name', content: '设计模式' }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['link', { rel: 'icon', href: '/favicon.svg', type: 'image/svg+xml' }],
    ['link', { rel: 'icon', href: '/favicon.ico', type: 'image/x-icon' }],
    ['link', { rel: 'apple-touch-icon', href: '/apple-touch-icon.png', sizes: '180x180' }],
  ],
  themeConfig: {
    siteTitle: '设计模式',

    // === 统一 nav（C1 规范：顶部 7 项 + 跨站 dropdown）===
    // 1) 门户  2) 首页  3) 知识图谱  4) 思维导图  5) 命令速查  6) 学习路径  7) 更多站点 ▼
    nav: [
      { text: '🏠 门户', link: 'https://java-px.bot.cd/', target: '_blank' },
      { text: '首页', link: '/' },
      { text: '知识图谱', link: '/graph' },
      { text: '思维导图', link: '/mindmap' },
      { text: '命令速查', link: '/cheatsheet' },
      { text: '学习路径', link: '/path' },
      {
        text: '更多站点',
        items: [
                  { text: "ElasticSearch", link: "https://java-px.bot.cd/es/" },
        { text: "MySQL", link: "https://java-px.bot.cd/mysql/" },
        { text: "Redis", link: "https://java-px.bot.cd/redis/" },
        { text: "微服务 / Spring Cloud", link: "https://java-px.bot.cd/cloud/" },
        { text: "Python", link: "https://java-px.bot.cd/python/" },
        { text: "Kafka", link: "https://java-px.bot.cd/kafka/" },
        { text: "Java Web 开发", link: "https://java-px.bot.cd/java/" },
        { text: "在线工具", link: "https://java-px.bot.cd/tools/" },
        { text: "前端 & Node", link: "https://java-px.bot.cd/frontend/" },
        { text: "Linux 服务器", link: "https://java-px.bot.cd/linux/" },
        { text: "云原生 / Docker / K8s", link: "https://java-px.bot.cd/cloud-native/" },
        { text: "AI 工具 / 大模型", link: "https://java-px.bot.cd/ai/" },
        { text: "大数据", link: "https://java-px.bot.cd/bigdata/" },
        { text: "计算机网络", link: "https://java-px.bot.cd/network/" },
        { text: "视频处理", link: "https://java-px.bot.cd/video/" },
        { text: "文件系统与存储", link: "https://java-px.bot.cd/filesystem/" },
        { text: "Java 语言", link: "https://java-px.bot.cd/java-language/" },
        { text: "企业级架构", link: "https://java-px.bot.cd/architecture/" },
        { text: "系统设计", link: "https://java-px.bot.cd/system-design/" },
        { text: "PostgreSQL", link: "https://java-px.bot.cd/postgresql/" },
        { text: "可观测性", link: "https://java-px.bot.cd/observability/" },
        { text: "安全", link: "https://java-px.bot.cd/security/" },
        { text: "DevOps", link: "https://java-px.bot.cd/devops/" },
        { text: "Rust", link: "https://java-px.bot.cd/rust/" },
        { text: "Go", link: "https://java-px.bot.cd/go/" },
        { text: "ClickHouse", link: "https://java-px.bot.cd/clickhouse/" },
        { text: "混沌工程", link: "https://java-px.bot.cd/chaos/" },
        { text: "物联网", link: "https://java-px.bot.cd/iot/" },
        { text: "安卓", link: "https://java-px.bot.cd/android/" },
        { text: "游戏开发", link: "https://java-px.bot.cd/game/" },
        ]
      }
    ],

    // === 各站独立 sidebar（render-config.py 保留原值）===
    sidebar: {
    
        
            
                
                                      '/': [
                                        {
                                          text: '🏗️ GoF 创建型模式', collapsed: false, items: [
                                            { text: '创建型总览', link: '/01-gof-creational/overview' },
                                            { text: 'Singleton 单例', link: '/01-gof-creational/singleton' },
                                            { text: 'Factory Method 工厂方法', link: '/01-gof-creational/factory-method' },
                                            { text: 'Abstract Factory 抽象工厂', link: '/01-gof-creational/abstract-factory' },
                                            { text: 'Builder 建造者', link: '/01-gof-creational/builder' },
                                            { text: 'Prototype 原型', link: '/01-gof-creational/prototype' }
                                          ]
                                        },
                                        {
                                          text: '🧩 GoF 结构型模式', collapsed: false, items: [
                                            { text: '结构型总览', link: '/02-gof-structural/overview' },
                                            { text: 'Adapter 适配器', link: '/02-gof-structural/adapter' },
                                            { text: 'Bridge 桥接', link: '/02-gof-structural/bridge' },
                                            { text: 'Composite 组合', link: '/02-gof-structural/composite' },
                                            { text: 'Decorator 装饰器', link: '/02-gof-structural/decorator' },
                                            { text: 'Facade 外观', link: '/02-gof-structural/facade' },
                                            { text: 'Flyweight 享元', link: '/02-gof-structural/flyweight' },
                                            { text: 'Proxy 代理', link: '/02-gof-structural/proxy' }
                                          ]
                                        },
                                        {
                                          text: '🎭 GoF 行为型模式', collapsed: false, items: [
                                            { text: '行为型总览', link: '/03-gof-behavioral/overview' },
                                            { text: 'Chain of Responsibility 责任链', link: '/03-gof-behavioral/chain-of-responsibility' },
                                            { text: 'Command 命令', link: '/03-gof-behavioral/command' },
                                            { text: 'Iterator 迭代器', link: '/03-gof-behavioral/iterator' },
                                            { text: 'Mediator 中介者', link: '/03-gof-behavioral/mediator' },
                                            { text: 'Memento 备忘录', link: '/03-gof-behavioral/memento' },
                                            { text: 'Observer 观察者', link: '/03-gof-behavioral/observer' },
                                            { text: 'State 状态', link: '/03-gof-behavioral/state' },
                                            { text: 'Strategy 策略', link: '/03-gof-behavioral/strategy' },
                                            { text: 'Template Method 模板方法', link: '/03-gof-behavioral/template-method' },
                                            { text: 'Visitor 访问者', link: '/03-gof-behavioral/visitor' },
                                            { text: 'Interpreter 解释器', link: '/03-gof-behavioral/interpreter' }
                                          ]
                                        },
                                        {
                                          text: '✨ 现代模式', collapsed: false, items: [
                                            { text: '现代模式总览', link: '/04-modern-patterns/overview' },
                                            { text: '依赖注入 DI', link: '/04-modern-patterns/dependency-injection' },
                                            { text: 'Repository 仓储', link: '/04-modern-patterns/repository' },
                                            { text: 'Specification 规格', link: '/04-modern-patterns/specification' },
                                            { text: 'Null Object 空对象', link: '/04-modern-patterns/null-object' }
                                          ]
                                        },
                                        {
                                          text: '🌐 架构模式', collapsed: false, items: [
                                            { text: '架构模式总览', link: '/05-architectural-patterns/overview' },
                                            { text: 'CQRS 命令查询分离', link: '/05-architectural-patterns/cqrs' },
                                            { text: 'Event Sourcing 事件溯源', link: '/05-architectural-patterns/event-sourcing' },
                                            { text: 'Saga 分布式事务', link: '/05-architectural-patterns/saga' },
                                            { text: 'Sidecar 边车', link: '/05-architectural-patterns/sidecar' },
                                            { text: 'Circuit Breaker 熔断', link: '/05-architectural-patterns/circuit-breaker' },
                                            { text: 'Bulkhead 舱壁隔离', link: '/05-architectural-patterns/bulkhead' },
                                            { text: 'Strangler Fig 绞杀者', link: '/05-architectural-patterns/strangler-fig' },
                                            { text: 'Outbox 事务性发件箱', link: '/05-architectural-patterns/outbox' }
                                          ]
                                        },
                                        {
                                          text: '🚫 反模式', collapsed: false, items: [
                                            { text: '反模式总览', link: '/06-anti-patterns/overview' },
                                            { text: 'God Object 上帝对象', link: '/06-anti-patterns/god-object' },
                                            { text: 'Anemic Model 贫血模型', link: '/06-anti-patterns/anemic-model' },
                                            { text: 'Big Ball of Mud 大泥球', link: '/06-anti-patterns/big-ball-of-mud' },
                                            { text: 'Callback Hell 回调地狱', link: '/06-anti-patterns/callback-hell' },
                                            { text: 'Circular Dependency 循环依赖', link: '/06-anti-patterns/circular-dependency' },
                                            { text: 'Magic Number 魔数', link: '/06-anti-patterns/magic-number' },
                                            { text: 'Premature Optimization 提前优化', link: '/06-anti-patterns/premature-optimization' }
                                          ]
                                        }
                                      ]
    },

    socialLinks: [],

    outline: { level: [2, 3], label: '页面大纲' },
    docFooter: { prev: '上一篇', next: '下一篇' },
    search: { provider: 'local' },

    footer: {
      message: '设计模式是面向对象编程与软件工程的核心抽象武器 · <a href="https://en.wikipedia.org/wiki/Design_Patterns" target="_blank">GoF 1994</a> · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>',
      copyright: 'MIT License'
    },
  }
}))
