/**
 * @generated from shared-assets/vitepress-template/config.mts.tpl
 * DO NOT EDIT THIS FILE DIRECTLY — edit the template and re-run render-config.py
 *
 * 模板变量（render-config.py 替换）：
 *   cloud         e.g. "ai", "java", "clickhouse"
 *   /cloud/       e.g. "/ai/", "/clickhouse/"
 *   Spring Cloud Alibaba 知识图谱      e.g. "AI 工程全栈"
 *   Spring Boot + Spring Cloud Alibaba 系统化学习 - 用知识图谱串联微服务组件       e.g. "系统化学习 AI 工具..."
 *   #6DB33F     e.g. "#8b5cf6"
 *   zh-CN       e.g. "zh-CN"
 *   Spring Cloud Alibaba 知识图谱 - 系统化学习微服务 · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>  e.g. "AI 工程全栈 - 工具 / 大模型 / SDK / Agent"
 *   [
      { icon: 'github', link: 'https://github.com' }
    ]   e.g. '[{ icon: "github", link: "https://github.com" }]'
 */
import { defineConfig } from 'vitepress'
import { withMermaid } from 'vitepress-plugin-mermaid'
import { fileURLToPath, URL } from 'node:url'

// P0: VitePress/rollup 默认 fs.allow 限制 cwd 外 import。用 vite alias 解决相对路径。
const SHARED_ASSETS = fileURLToPath(new URL('../../shared-assets', import.meta.url))

// C11: Mermaid 跨站共享配置（inline 而非 import，避免 vite alias 在 Node 加载 config.mts 阶段不生效的问题）
// 同步源：shared-assets/mermaid-config/base.ts（修改时请同步更新此处）
// 见 §8.46
const mermaidBase = {
  securityLevel: 'loose',
  startOnLoad: false,
  theme: 'base',
  fontFamily: '"Inter", "PingFang SC", "Microsoft YaHei", system-ui, -apple-system, sans-serif',
} as const

function lightenHex(hex: string, ratio: number): string {
  const m = hex.replace('#', '').match(/^([0-9a-f]{6})$/i)
  if (!m) return hex
  const r = parseInt(m[1].slice(0, 2), 16)
  const g = parseInt(m[1].slice(2, 4), 16)
  const b = parseInt(m[1].slice(4, 6), 16)
  const mix = (c: number) => Math.round(c + (255 - c) * ratio)
  return '#' + [mix(r), mix(g), mix(b)].map(c => c.toString(16).padStart(2, '0')).join('')
}

function mermaidTheme(brand: string) {
  const soft = lightenHex(brand, 0.85)
  const ink = '#1f2937'
  const line = '#94a3b8'
  return {
    primaryColor: brand,
    primaryTextColor: ink,
    primaryBorderColor: brand,
    lineColor: line,
    secondaryColor: soft,
    tertiaryColor: '#fafafa',
    fontFamily: mermaidBase.fontFamily,
    fontSize: '14px',
  }
}

export default withMermaid( defineConfig({
  vite: {
    resolve: {
      alias: [
        { find: '@shared', replacement: SHARED_ASSETS },
      ],
    },
  },
    mermaid: {
    ...mermaidBase,
    themeVariables: mermaidTheme('#6DB33F'),
  },
    base: '/cloud/',
  title: 'Spring Cloud Alibaba 知识图谱',
  description: 'Spring Boot + Spring Cloud Alibaba 系统化学习 - 用知识图谱串联微服务组件',
  lang: 'zh-CN',
  lastUpdated: true,
  srcDir: 'docs',
  cleanUrls: true,
  ignoreDeadLinks: true,
  head: [
    ['meta', { name: 'viewport', content: 'width=device-width,initial-scale=1,viewport-fit=cover' }],
    ['meta', { name: 'theme-color', content: '#6DB33F' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:locale', content: 'zh_CN' }],
    ['meta', { property: 'og:site_name', content: 'Spring Cloud Alibaba 知识图谱' }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['link', { rel: 'icon', href: '/favicon.svg', type: 'image/svg+xml' }],
    ['link', { rel: 'icon', href: '/favicon.ico', type: 'image/x-icon' }],
    ['link', { rel: 'apple-touch-icon', href: '/apple-touch-icon.png', sizes: '180x180' }],
  ],
  themeConfig: {
    siteTitle: 'Spring Cloud Alibaba 知识图谱',

    // === 统一 nav（C1 规范：顶部 7 项 + 跨站 dropdown）===
    // 1) 门户  2) 首页  3) 知识图谱  4) 思维导图  5) 命令速查  6) 学习路径  7) 更多站点 ▼
    nav: [
      { text: '🏠 门户', link: 'https://java-px.bot.cd/', target: '_blank' },
      { text: '首页', link: '/' },
      { text: '知识图谱', link: '/graph' },
      { text: '思维导图', link: '/mindmap' },
      { text: '命令速查', link: '/cheatsheet' },
      { text: '学习路径', link: '/path' },
      {
        text: '更多站点',
        items: [
                  { text: "ElasticSearch", link: "https://java-px.bot.cd/es/" },
        { text: "MySQL", link: "https://java-px.bot.cd/mysql/" },
        { text: "Redis", link: "https://java-px.bot.cd/redis/" },
        { text: "Python", link: "https://java-px.bot.cd/python/" },
        { text: "Kafka", link: "https://java-px.bot.cd/kafka/" },
        { text: "Java Web 开发", link: "https://java-px.bot.cd/java/" },
        { text: "在线工具", link: "https://java-px.bot.cd/tools/" },
        { text: "前端 & Node", link: "https://java-px.bot.cd/frontend/" },
        { text: "Linux 服务器", link: "https://java-px.bot.cd/linux/" },
        { text: "云原生 / Docker / K8s", link: "https://java-px.bot.cd/cloud-native/" },
        { text: "AI 工具 / 大模型", link: "https://java-px.bot.cd/ai/" },
        { text: "大数据", link: "https://java-px.bot.cd/bigdata/" },
        { text: "计算机网络", link: "https://java-px.bot.cd/network/" },
        { text: "视频处理", link: "https://java-px.bot.cd/video/" },
        { text: "文件系统与存储", link: "https://java-px.bot.cd/filesystem/" },
        { text: "Java 语言", link: "https://java-px.bot.cd/java-language/" },
        { text: "企业级架构", link: "https://java-px.bot.cd/architecture/" },
        { text: "系统设计", link: "https://java-px.bot.cd/system-design/" },
        { text: "PostgreSQL", link: "https://java-px.bot.cd/postgresql/" },
        { text: "可观测性", link: "https://java-px.bot.cd/observability/" },
        { text: "安全", link: "https://java-px.bot.cd/security/" },
        { text: "DevOps", link: "https://java-px.bot.cd/devops/" },
        { text: "Rust", link: "https://java-px.bot.cd/rust/" },
        { text: "Go", link: "https://java-px.bot.cd/go/" },
        { text: "ClickHouse", link: "https://java-px.bot.cd/clickhouse/" },
        { text: "设计模式", link: "https://java-px.bot.cd/design-pattern/" },
        { text: "混沌工程", link: "https://java-px.bot.cd/chaos/" },
        { text: "物联网", link: "https://java-px.bot.cd/iot/" },
        { text: "安卓", link: "https://java-px.bot.cd/android/" },
        { text: "游戏开发", link: "https://java-px.bot.cd/game/" },
        ]
      }
    ],

    // === 各站独立 sidebar（render-config.py 保留原值）===
    sidebar: {
    
        
            
                
                                      '/': [
                                        {
                                          text: '🎯 开始',
                                          items: [
                                            { text: '📖 学习路径', link: '/path' }
                                          ]
                                        },
                                        {
                                          text: '🍃 Spring Boot 基础',
                                          items: [
                                            { text: '🚀 快速开始', link: '/01-springboot/quickstart' },
                                            { text: '⚙️ 自动配置原理', link: '/01-springboot/auto-config' },
                                            { text: '🌐 Web 开发', link: '/01-springboot/web' },
                                            { text: '💾 数据访问', link: '/01-springboot/data' },
                                            { text: '🔄 事务管理', link: '/01-springboot/transaction' }
                                          ]
                                        },
                                        {
                                          text: '☁️ Spring Cloud Alibaba 核心',
                                          items: [
                                            { text: '📚 Spring Cloud Alibaba 总览', link: '/02-overview/intro' },
                                            { text: '🌐 Nacos 服务发现', link: '/02-overview/nacos-discovery' },
                                            { text: '⚙️ Nacos 配置中心', link: '/02-overview/nacos-config' },
                                            { text: '⚡ Nacos 底层原理', link: '/02-overview/nacos-principle' }
                                          ]
                                        },
                                        {
                                          text: '🚪 微服务网关',
                                          items: [
                                            { text: '🌊 Gateway 基础', link: '/03-gateway/basic' },
                                            { text: '🛣️ 路由与断言', link: '/03-gateway/route' },
                                            { text: '🔧 过滤器', link: '/03-gateway/filter' }
                                          ]
                                        },
                                        {
                                          text: '⚖️ 负载均衡',
                                          items: [
                                            { text: '🔄 Spring Cloud LoadBalancer', link: '/04-loadbalancer/basic' },
                                            { text: '🎯 负载均衡策略', link: '/04-loadbalancer/strategy' }
                                          ]
                                        },
                                        {
                                          text: '🔐 认证授权',
                                          items: [
                                            { text: '🛡️ Spring Security 基础', link: '/05-security/basic' },
                                            { text: '🔑 OAuth2 + JWT 实战', link: '/05-security/oauth2' },
                                            { text: '🏛️ 统一认证中心', link: '/05-security/auth-center' }
                                          ]
                                        },
                                        {
                                          text: '🛠️ 实战与面试',
                                          items: [
                                            { text: '💼 综合实战项目', link: '/06-practice/comprehensive' },
                                            { text: '⚠️ 常见坑与最佳实践', link: '/06-practice/pitfalls' },
                                            { text: '🎯 高频面试题', link: '/06-practice/interview' }
                                          ]
                                        },
                                        {
                                          text: '🌐 分布式理论',
                                          items: [
                                            { text: '⚖️ CAP 与 BASE 理论', link: '/07-distributed/cap-base' },
                                            { text: '🏗️ 分布式架构模式', link: '/07-distributed/architecture' },
                                            { text: '🔐 分布式锁', link: '/07-distributed/distributed-lock' },
                                            { text: '💰 分布式事务', link: '/07-distributed/distributed-transaction' },
                                            { text: '🆔 分布式 ID', link: '/07-distributed/distributed-id' },
                                            { text: '💬 分布式消息队列', link: '/07-distributed/distributed-mq' },
                                            { text: '📊 分布式存储', link: '/07-distributed/distributed-storage' },
                                            { text: '🔄 分布式协调', link: '/07-distributed/distributed-coordination' },
                                            { text: '🔍 分布式追踪', link: '/07-distributed/distributed-tracing' },
                                            { text: '🛡️ 高可用与限流熔断', link: '/07-distributed/high-availability' }
                                          ]
                                        }
                                      ],
                                      '/graph': [
                                        {
                                          text: '🎯 知识图谱',
                                          items: [
                                            { text: '🌐 Spring Cloud 知识图谱', link: '/graph' }
                                          ]
                                        }
                                      ],
                                      '/mindmap': [
                                        {
                                          text: '🎯 思维导图',
                                          items: [
                                            { text: '🧭 Spring Cloud 思维导图', link: '/mindmap' }
                                          ]
                                        }
                                      ],
                                      '/cheatsheet': [
                                        {
                                          text: '🎯 组件速查',
                                          items: [
                                            { text: '📋 常用配置速查', link: '/cheatsheet' }
                                          ]
                                        }
                                      ],
                                      '/path': [
                                        {
                                          text: '🎯 学习路径',
                                          items: [
                                            { text: '📖 Spring Cloud 学习路径', link: '/path' }
                                          ]
                                        }
                                      ]
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com' }
    ],

    outline: { level: [2, 3], label: '页面大纲' },
    docFooter: { prev: '上一篇', next: '下一篇' },
    search: { provider: 'local' },

    footer: {
      message: 'Spring Cloud Alibaba 知识图谱 - 系统化学习微服务 · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>',
      copyright: 'MIT License'
    },
  }
}))
