/**
 * @generated from shared-assets/vitepress-template/config.mts.tpl
 * DO NOT EDIT THIS FILE DIRECTLY — edit the template and re-run render-config.py
 *
 * 模板变量（render-config.py 替换）：
 *   go         e.g. "ai", "java", "clickhouse"
 *   /go/       e.g. "/ai/", "/clickhouse/"
 *   Go      e.g. "AI 工程全栈"
 *   云原生 + 后端微服务深度图谱 - 基础语法 / CSP 并发模型 / goroutine / channel / context · Go 工具链 / 标准库 / 测试 · Docker / Kubernetes / Prometheus / etcd 源码导读 · Gin / gRPC / Kratos 微服务 · runtime GMP / GC / pprof · 6 大类 · 35 节点       e.g. "系统化学习 AI 工具..."
 *   #00ADD8     e.g. "#8b5cf6"
 *   zh-CN       e.g. "zh-CN"
 *   本站点基于 VitePress 构建 · CC BY-NC-SA 4.0 · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>  e.g. "AI 工程全栈 - 工具 / 大模型 / SDK / Agent"
 *   []   e.g. '[{ icon: "github", link: "https://github.com" }]'
 */
import { defineConfig } from 'vitepress'
import { fileURLToPath, URL } from 'node:url'

// P0: VitePress/rollup 默认 fs.allow 限制 cwd 外 import。用 vite alias 解决相对路径。
const SHARED_ASSETS = fileURLToPath(new URL('../../shared-assets', import.meta.url))

export default defineConfig({
  vite: {
    resolve: {
      alias: [
        { find: '@shared', replacement: SHARED_ASSETS },
      ],
    },
    // §8.72：shared-assets/svg/ 共享 SVG 资产（CAP / Saga / 一致性 hash 等）
    publicDir: fileURLToPath(new URL('../../shared-assets/svg', import.meta.url)),
  },
  base: '/go/',
  title: 'Go',
  description: '云原生 + 后端微服务深度图谱 - 基础语法 / CSP 并发模型 / goroutine / channel / context · Go 工具链 / 标准库 / 测试 · Docker / Kubernetes / Prometheus / etcd 源码导读 · Gin / gRPC / Kratos 微服务 · runtime GMP / GC / pprof · 6 大类 · 35 节点',
  lang: 'zh-CN',
  lastUpdated: true,
  srcDir: 'docs',
  cleanUrls: true,
  ignoreDeadLinks: true,
  head: [
    ['meta', { name: 'viewport', content: 'width=device-width,initial-scale=1,viewport-fit=cover' }],
    ['meta', { name: 'theme-color', content: '#00ADD8' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:locale', content: 'zh_CN' }],
    ['meta', { property: 'og:site_name', content: 'Go' }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['link', { rel: 'icon', href: '/favicon.svg', type: 'image/svg+xml' }],
    ['link', { rel: 'icon', href: '/favicon.ico', type: 'image/x-icon' }],
    ['link', { rel: 'apple-touch-icon', href: '/apple-touch-icon.png', sizes: '180x180' }],
  ],
  themeConfig: {
    siteTitle: 'Go',

    // === 统一 nav（C1 规范：顶部 7 项 + 跨站 dropdown）===
    // 1) 门户  2) 首页  3) 知识图谱  4) 思维导图  5) 命令速查  6) 学习路径  7) 更多站点 ▼
    nav: [
      { text: '🏠 门户', link: 'https://java-px.bot.cd/', target: '_blank' },
      { text: '首页', link: '/' },
      { text: '知识图谱', link: '/graph' },
      { text: '思维导图', link: '/mindmap' },
      { text: '命令速查', link: '/cheatsheet' },
      { text: '学习路径', link: '/path' },
      {
        text: '更多站点',
        items: [
                  { text: "ElasticSearch", link: "https://java-px.bot.cd/es/" },
        { text: "MySQL", link: "https://java-px.bot.cd/mysql/" },
        { text: "Redis", link: "https://java-px.bot.cd/redis/" },
        { text: "微服务 / Spring Cloud", link: "https://java-px.bot.cd/cloud/" },
        { text: "Python", link: "https://java-px.bot.cd/python/" },
        { text: "Kafka", link: "https://java-px.bot.cd/kafka/" },
        { text: "Java Web 开发", link: "https://java-px.bot.cd/java/" },
        { text: "在线工具", link: "https://java-px.bot.cd/tools/" },
        { text: "前端 & Node", link: "https://java-px.bot.cd/frontend/" },
        { text: "Linux 服务器", link: "https://java-px.bot.cd/linux/" },
        { text: "云原生 / Docker / K8s", link: "https://java-px.bot.cd/cloud-native/" },
        { text: "AI 工具 / 大模型", link: "https://java-px.bot.cd/ai/" },
        { text: "大数据", link: "https://java-px.bot.cd/bigdata/" },
        { text: "计算机网络", link: "https://java-px.bot.cd/network/" },
        { text: "视频处理", link: "https://java-px.bot.cd/video/" },
        { text: "文件系统与存储", link: "https://java-px.bot.cd/filesystem/" },
        { text: "Java 语言", link: "https://java-px.bot.cd/java-language/" },
        { text: "企业级架构", link: "https://java-px.bot.cd/architecture/" },
        { text: "系统设计", link: "https://java-px.bot.cd/system-design/" },
        { text: "PostgreSQL", link: "https://java-px.bot.cd/postgresql/" },
        { text: "可观测性", link: "https://java-px.bot.cd/observability/" },
        { text: "安全", link: "https://java-px.bot.cd/security/" },
        { text: "DevOps", link: "https://java-px.bot.cd/devops/" },
        { text: "Rust", link: "https://java-px.bot.cd/rust/" },
        { text: "ClickHouse", link: "https://java-px.bot.cd/clickhouse/" },
        { text: "设计模式", link: "https://java-px.bot.cd/design-pattern/" },
        { text: "混沌工程", link: "https://java-px.bot.cd/chaos/" },
        { text: "物联网", link: "https://java-px.bot.cd/iot/" },
        { text: "安卓", link: "https://java-px.bot.cd/android/" },
        { text: "游戏开发", link: "https://java-px.bot.cd/game/" },
        ]
      }
    ],

    // === 各站独立 sidebar（render-config.py 保留原值）===
    sidebar: {
    
        
            
                
                                      '/': [
                                        {
                                          text: '🐹 Go 基础', collapsed: false, items: [
                                            { text: 'Go 总览', link: '/01-basics/overview' },
                                            { text: '语法速览', link: '/01-basics/syntax-fundamentals' },
                                            { text: '类型与函数', link: '/01-basics/types-and-functions' },
                                            { text: '错误处理', link: '/01-basics/error-handling' },
                                            { text: '包与模块管理', link: '/01-basics/package-and-module' },
                                            { text: 'Hello World 实战', link: '/01-basics/hello-world' }
                                          ]
                                        },
                                        {
                                          text: '⚡ 并发模型', collapsed: false, items: [
                                            { text: 'CSP 并发总览', link: '/02-concurrency/overview' },
                                            { text: 'goroutine', link: '/02-concurrency/goroutine' },
                                            { text: 'channel', link: '/02-concurrency/channel' },
                                            { text: 'sync 包', link: '/02-concurrency/sync-package' },
                                            { text: 'context 上下文', link: '/02-concurrency/context' },
                                            { text: '并发模式实战', link: '/02-concurrency/patterns' }
                                          ]
                                        },
                                        {
                                          text: '🔧 生态与工具链', collapsed: false, items: [
                                            { text: 'Go 生态总览', link: '/03-ecosystem/overview' },
                                            { text: 'Go 工具链', link: '/03-ecosystem/go-toolchain' },
                                            { text: '标准库', link: '/03-ecosystem/standard-library' },
                                            { text: '测试与覆盖率', link: '/03-ecosystem/testing' },
                                            { text: '性能基准与 pprof', link: '/03-ecosystem/benchmark' }
                                          ]
                                        },
                                        {
                                          text: '☁️ 云原生生态', collapsed: false, items: [
                                            { text: '云原生总览', link: '/04-cloud-native/overview' },
                                            { text: 'Docker 源码导读', link: '/04-cloud-native/docker-internals' },
                                            { text: 'Kubernetes 源码导读', link: '/04-cloud-native/kubernetes-internals' },
                                            { text: 'Prometheus 源码导读', link: '/04-cloud-native/prometheus-internals' },
                                            { text: 'etcd 源码导读', link: '/04-cloud-native/etcd-internals' },
                                            { text: 'CNCF 项目全景', link: '/04-cloud-native/cncf-ecosystem' }
                                          ]
                                        },
                                        {
                                          text: '🌐 后端微服务', collapsed: false, items: [
                                            { text: '微服务总览', link: '/05-microservices/overview' },
                                            { text: 'Gin 框架', link: '/05-microservices/gin-framework' },
                                            { text: 'gRPC + Protobuf', link: '/05-microservices/grpc' },
                                            { text: 'Kratos / go-zero / go-micro', link: '/05-microservices/kratos' },
                                            { text: '服务治理', link: '/05-microservices/service-governance' },
                                            { text: '微服务案例研究', link: '/05-microservices/case-study' }
                                          ]
                                        },
                                        {
                                          text: '🚀 进阶与 runtime', collapsed: false, items: [
                                            { text: '进阶总览', link: '/06-advanced/overview' },
                                            { text: 'runtime 调度器 GMP', link: '/06-advanced/runtime' },
                                            { text: 'GC 三色标记', link: '/06-advanced/gc' },
                                            { text: 'pprof 与 trace', link: '/06-advanced/pprof' },
                                            { text: 'cgo 与 FFI', link: '/06-advanced/cgo' },
                                            { text: '反射 reflect', link: '/06-advanced/reflection' }
                                          ]
                                        }
                                      ]
    },

    socialLinks: [],

    outline: { level: [2, 3], label: '页面大纲' },
    docFooter: { prev: '上一篇', next: '下一篇' },
    search: { provider: 'local' },

    footer: {
      message: '本站点基于 VitePress 构建 · CC BY-NC-SA 4.0 · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>',
      copyright: 'MIT License'
    },
  }
})
