/**
 * @generated from shared-assets/vitepress-template/config.mts.tpl
 * DO NOT EDIT THIS FILE DIRECTLY — edit the template and re-run render-config.py
 *
 * 模板变量（render-config.py 替换）：
 *   devops         e.g. "ai", "java", "clickhouse"
 *   /devops/       e.g. "/ai/", "/clickhouse/"
 *   DevOps      e.g. "AI 工程全栈"
 *   软件交付链深度图谱 - CI/CD Pipeline · IaC · GitOps · 蓝绿 / 灰度 / 金丝雀 · DORA Metrics · 6 大类 · 29 节点       e.g. "系统化学习 AI 工具..."
 *   #06b6d4     e.g. "#8b5cf6"
 *   zh-CN       e.g. "zh-CN"
 *   本站点基于 VitePress 构建 · CC BY-NC-SA 4.0 · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>  e.g. "AI 工程全栈 - 工具 / 大模型 / SDK / Agent"
 *   []   e.g. '[{ icon: "github", link: "https://github.com" }]'
 */
import { defineConfig } from 'vitepress'
import { fileURLToPath, URL } from 'node:url'

// P0: VitePress/rollup 默认 fs.allow 限制 cwd 外 import。用 vite alias 解决相对路径。
const SHARED_ASSETS = fileURLToPath(new URL('../../shared-assets', import.meta.url))

export default defineConfig({
  vite: {
    resolve: {
      alias: [
        { find: '@shared', replacement: SHARED_ASSETS },
      ],
    },
    // §8.72：shared-assets/svg/ 共享 SVG 资产（CAP / Saga / 一致性 hash 等）
    publicDir: fileURLToPath(new URL('../../shared-assets/svg', import.meta.url)),
  },
  base: '/devops/',
  title: 'DevOps',
  description: '软件交付链深度图谱 - CI/CD Pipeline · IaC · GitOps · 蓝绿 / 灰度 / 金丝雀 · DORA Metrics · 6 大类 · 29 节点',
  lang: 'zh-CN',
  lastUpdated: true,
  srcDir: 'docs',
  cleanUrls: true,
  ignoreDeadLinks: true,
  head: [
    ['meta', { name: 'viewport', content: 'width=device-width,initial-scale=1,viewport-fit=cover' }],
    ['meta', { name: 'theme-color', content: '#06b6d4' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:locale', content: 'zh_CN' }],
    ['meta', { property: 'og:site_name', content: 'DevOps' }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['link', { rel: 'icon', href: '/favicon.svg', type: 'image/svg+xml' }],
    ['link', { rel: 'icon', href: '/favicon.ico', type: 'image/x-icon' }],
    ['link', { rel: 'apple-touch-icon', href: '/apple-touch-icon.png', sizes: '180x180' }],
  ],
  themeConfig: {
    siteTitle: 'DevOps',

    // === 统一 nav（C1 规范：顶部 7 项 + 跨站 dropdown）===
    // 1) 门户  2) 首页  3) 知识图谱  4) 思维导图  5) 命令速查  6) 学习路径  7) 更多站点 ▼
    nav: [
      { text: '🏠 门户', link: 'https://java-px.bot.cd/', target: '_blank' },
      { text: '首页', link: '/' },
      { text: '知识图谱', link: '/graph' },
      { text: '思维导图', link: '/mindmap' },
      { text: '命令速查', link: '/cheatsheet' },
      { text: '学习路径', link: '/path' },
      {
        text: '更多站点',
        items: [
                  { text: "ElasticSearch", link: "https://java-px.bot.cd/es/" },
        { text: "MySQL", link: "https://java-px.bot.cd/mysql/" },
        { text: "Redis", link: "https://java-px.bot.cd/redis/" },
        { text: "微服务 / Spring Cloud", link: "https://java-px.bot.cd/cloud/" },
        { text: "Python", link: "https://java-px.bot.cd/python/" },
        { text: "Kafka", link: "https://java-px.bot.cd/kafka/" },
        { text: "Java Web 开发", link: "https://java-px.bot.cd/java/" },
        { text: "在线工具", link: "https://java-px.bot.cd/tools/" },
        { text: "前端 & Node", link: "https://java-px.bot.cd/frontend/" },
        { text: "Linux 服务器", link: "https://java-px.bot.cd/linux/" },
        { text: "云原生 / Docker / K8s", link: "https://java-px.bot.cd/cloud-native/" },
        { text: "AI 工具 / 大模型", link: "https://java-px.bot.cd/ai/" },
        { text: "大数据", link: "https://java-px.bot.cd/bigdata/" },
        { text: "计算机网络", link: "https://java-px.bot.cd/network/" },
        { text: "视频处理", link: "https://java-px.bot.cd/video/" },
        { text: "文件系统与存储", link: "https://java-px.bot.cd/filesystem/" },
        { text: "Java 语言", link: "https://java-px.bot.cd/java-language/" },
        { text: "企业级架构", link: "https://java-px.bot.cd/architecture/" },
        { text: "系统设计", link: "https://java-px.bot.cd/system-design/" },
        { text: "PostgreSQL", link: "https://java-px.bot.cd/postgresql/" },
        { text: "可观测性", link: "https://java-px.bot.cd/observability/" },
        { text: "安全", link: "https://java-px.bot.cd/security/" },
        { text: "Rust", link: "https://java-px.bot.cd/rust/" },
        { text: "Go", link: "https://java-px.bot.cd/go/" },
        { text: "ClickHouse", link: "https://java-px.bot.cd/clickhouse/" },
        { text: "设计模式", link: "https://java-px.bot.cd/design-pattern/" },
        { text: "混沌工程", link: "https://java-px.bot.cd/chaos/" },
        { text: "物联网", link: "https://java-px.bot.cd/iot/" },
        { text: "安卓", link: "https://java-px.bot.cd/android/" },
        { text: "游戏开发", link: "https://java-px.bot.cd/game/" },
        ]
      }
    ],

    // === 各站独立 sidebar（render-config.py 保留原值）===
    sidebar: {
    
        
            
                
                                      '/': [
                                        {
                                          text: '⚙️ CI/CD Pipeline', collapsed: false, items: [
                                            { text: 'Pipeline 总览', link: '/01-pipeline/overview' },
                                            { text: 'GitHub Actions', link: '/01-pipeline/github-actions' },
                                            { text: 'GitLab CI', link: '/01-pipeline/gitlab-ci' },
                                            { text: 'Jenkins', link: '/01-pipeline/jenkins' },
                                            { text: 'Tekton', link: '/01-pipeline/tekton' },
                                            { text: 'Pipeline 最佳实践', link: '/01-pipeline/best-practices' }
                                          ]
                                        },
                                        {
                                          text: '🏗️ IaC 基础设施即代码', collapsed: false, items: [
                                            { text: 'IaC 总览', link: '/02-iac/overview' },
                                            { text: 'Terraform', link: '/02-iac/terraform' },
                                            { text: 'Pulumi', link: '/02-iac/pulumi' },
                                            { text: 'Ansible', link: '/02-iac/ansible' },
                                            { text: 'Terraform vs Pulumi', link: '/02-iac/terraform-vs-pulumi' }
                                          ]
                                        },
                                        {
                                          text: '🔄 GitOps', collapsed: false, items: [
                                            { text: 'GitOps 总览', link: '/03-gitops/overview' },
                                            { text: 'ArgoCD', link: '/03-gitops/argocd' },
                                            { text: 'Flux', link: '/03-gitops/flux' },
                                            { text: 'Progressive Delivery', link: '/03-gitops/progressive-delivery' }
                                          ]
                                        },
                                        {
                                          text: '🚀 发布策略', collapsed: false, items: [
                                            { text: '发布策略总览', link: '/04-release/overview' },
                                            { text: '蓝绿部署', link: '/04-release/blue-green' },
                                            { text: '金丝雀发布', link: '/04-release/canary' },
                                            { text: 'Feature Flag', link: '/04-release/feature-flag' },
                                            { text: '回滚机制', link: '/04-release/rollback' }
                                          ]
                                        },
                                        {
                                          text: '📊 CI/CD 可观测性', collapsed: false, items: [
                                            { text: '流水线可观测性', link: '/05-cicd-observability/overview' },
                                            { text: 'DORA Metrics', link: '/05-cicd-observability/dora-metrics' },
                                            { text: 'Flaky Test', link: '/05-cicd-observability/flaky-test' },
                                            { text: 'Pipeline 监控', link: '/05-cicd-observability/pipeline-monitoring' }
                                          ]
                                        },
                                        {
                                          text: '⭐ 最佳实践', collapsed: false, items: [
                                            { text: '构建缓存', link: '/06-best-practices/caching' },
                                            { text: '安全流水线', link: '/06-best-practices/secure-pipeline' },
                                            { text: 'Secrets 管理', link: '/06-best-practices/secrets-management' },
                                            { text: 'OIDC 联邦', link: '/06-best-practices/oidc-federation' },
                                            { text: '案例研究', link: '/06-best-practices/case-study' }
                                          ]
                                        }
                                      ]
    },

    socialLinks: [],

    outline: { level: [2, 3], label: '页面大纲' },
    docFooter: { prev: '上一篇', next: '下一篇' },
    search: { provider: 'local' },

    footer: {
      message: '本站点基于 VitePress 构建 · CC BY-NC-SA 4.0 · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>',
      copyright: 'MIT License'
    },
  }
})
