/**
 * @generated from shared-assets/vitepress-template/config.mts.tpl
 * DO NOT EDIT THIS FILE DIRECTLY — edit the template and re-run render-config.py
 *
 * 模板变量（render-config.py 替换）：
 *   ai         e.g. "ai", "java", "clickhouse"
 *   /ai/       e.g. "/ai/", "/clickhouse/"
 *   AI 工程全栈      e.g. "AI 工程全栈"
 *   系统化学习 AI 工具、主流大模型、SDK 与 Agent 框架 - 14 大类 · 80+ 节点 · 60+ 内容页       e.g. "系统化学习 AI 工具..."
 *   #8b5cf6     e.g. "#8b5cf6"
 *   zh-CN       e.g. "zh-CN"
 *   AI 工程全栈 - 工具 / 大模型 / SDK / Agent · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>  e.g. "AI 工程全栈 - 工具 / 大模型 / SDK / Agent"
 *   [{ icon: 'github', link: 'https://github.com' }]   e.g. '[{ icon: "github", link: "https://github.com" }]'
 */
import { defineConfig } from 'vitepress'
import { fileURLToPath, URL } from 'node:url'

// P0: VitePress/rollup 默认 fs.allow 限制 cwd 外 import。用 vite alias 解决相对路径。
const SHARED_ASSETS = fileURLToPath(new URL('../../shared-assets', import.meta.url))

// P0: shared-assets/ 下的 .vue 组件 import vue 时需要显式 alias 指向本站点 node_modules。
// 否则 rollup 在 SHARED_ASSETS 目录找不到 vue，会报 "Rollup failed to resolve import 'vue'"。
// §8.81 QrShare 落地后暴露此问题。
// §8.81 二次修复：alias 还要覆盖 vue 子路径（vue/server-renderer · vue/compiler-sfc 等）
// 否则 vitepress SSR 阶段 import 'vue/server-renderer' 仍会 resolve 失败。
const VUE_DIR = fileURLToPath(new URL('../node_modules/vue/', import.meta.url))

export default defineConfig({
  vite: {
    resolve: {
      alias: [
        { find: '@shared', replacement: SHARED_ASSETS },
        { find: /^vue(\/.*)?$/, replacement: `${VUE_DIR}$1` },
      ],
    },
    // §8.72：shared-assets/svg/ 共享 SVG 资产（CAP / Saga / 一致性 hash 等）
    // 只把 svg/ 子目录作为 public（避免泄漏 mermaid-config / glossary / template 等）
    publicDir: fileURLToPath(new URL('../../shared-assets/svg', import.meta.url)),
  },
  base: '/ai/',
  title: 'AI 工程全栈',
  description: '系统化学习 AI 工具、主流大模型、SDK 与 Agent 框架 - 14 大类 · 80+ 节点 · 60+ 内容页',
  lang: 'zh-CN',
  lastUpdated: true,
  srcDir: 'docs',
  cleanUrls: true,
  ignoreDeadLinks: true,
  head: [
    ['meta', { name: 'viewport', content: 'width=device-width,initial-scale=1,viewport-fit=cover' }],
    ['meta', { name: 'theme-color', content: '#8b5cf6' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:locale', content: 'zh_CN' }],
    ['meta', { property: 'og:site_name', content: 'AI 工程全栈' }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['link', { rel: 'icon', href: '/favicon.svg', type: 'image/svg+xml' }],
    ['link', { rel: 'icon', href: '/favicon.ico', type: 'image/x-icon' }],
    ['link', { rel: 'apple-touch-icon', href: '/apple-touch-icon.png', sizes: '180x180' }],
  ],
  themeConfig: {
    siteTitle: 'AI 工程全栈',

    // === 统一 nav（C1 规范：顶部 7 项 + 跨站 dropdown）===
    // 1) 门户  2) 首页  3) 知识图谱  4) 思维导图  5) 命令速查  6) 学习路径  7) 更多站点 ▼
    nav: [
      { text: '🏠 门户', link: 'https://java-px.bot.cd/', target: '_blank' },
      { text: '首页', link: '/' },
      { text: '知识图谱', link: '/graph' },
      { text: '思维导图', link: '/mindmap' },
      { text: '命令速查', link: '/cheatsheet' },
      { text: '学习路径', link: '/path' },
      {
        text: '更多站点',
        items: [
                  { text: "ElasticSearch", link: "https://java-px.bot.cd/es/" },
        { text: "MySQL", link: "https://java-px.bot.cd/mysql/" },
        { text: "Redis", link: "https://java-px.bot.cd/redis/" },
        { text: "微服务 / Spring Cloud", link: "https://java-px.bot.cd/cloud/" },
        { text: "Python", link: "https://java-px.bot.cd/python/" },
        { text: "Kafka", link: "https://java-px.bot.cd/kafka/" },
        { text: "Java Web 开发", link: "https://java-px.bot.cd/java/" },
        { text: "在线工具", link: "https://java-px.bot.cd/tools/" },
        { text: "前端 & Node", link: "https://java-px.bot.cd/frontend/" },
        { text: "Linux 服务器", link: "https://java-px.bot.cd/linux/" },
        { text: "云原生 / Docker / K8s", link: "https://java-px.bot.cd/cloud-native/" },
        { text: "大数据", link: "https://java-px.bot.cd/bigdata/" },
        { text: "计算机网络", link: "https://java-px.bot.cd/network/" },
        { text: "视频处理", link: "https://java-px.bot.cd/video/" },
        { text: "文件系统与存储", link: "https://java-px.bot.cd/filesystem/" },
        { text: "Java 语言", link: "https://java-px.bot.cd/java-language/" },
        { text: "企业级架构", link: "https://java-px.bot.cd/architecture/" },
        { text: "系统设计", link: "https://java-px.bot.cd/system-design/" },
        { text: "PostgreSQL", link: "https://java-px.bot.cd/postgresql/" },
        { text: "可观测性", link: "https://java-px.bot.cd/observability/" },
        { text: "安全", link: "https://java-px.bot.cd/security/" },
        { text: "DevOps", link: "https://java-px.bot.cd/devops/" },
        { text: "Rust", link: "https://java-px.bot.cd/rust/" },
        { text: "Go", link: "https://java-px.bot.cd/go/" },
        { text: "ClickHouse", link: "https://java-px.bot.cd/clickhouse/" },
        { text: "设计模式", link: "https://java-px.bot.cd/design-pattern/" },
        { text: "混沌工程", link: "https://java-px.bot.cd/chaos/" },
        { text: "物联网", link: "https://java-px.bot.cd/iot/" },
        { text: "安卓", link: "https://java-px.bot.cd/android/" },
        { text: "游戏开发", link: "https://java-px.bot.cd/game/" },
        ]
      }
    ],

    // === 各站独立 sidebar（render-config.py 保留原值）===
    sidebar: {
    
        
            
                
                    
                        
                            
                                
                                    
                                        
                                            
                                                                                              '/': [
                                                                                                { text: '🎯 开始', items: [{ text: '📖 学习路径', link: '/path' }] },
                                                                                                {
                                                                                                  text: '🧠 大模型与推理', items: [
                                                                                                    { text: 'Claude 模型家族', link: '/01-models/claude' },
                                                                                                    { text: 'GPT / OpenAI', link: '/01-models/gpt' },
                                                                                                    { text: 'Gemini', link: '/01-models/gemini' },
                                                                                                    { text: 'DeepSeek', link: '/01-models/deepseek' },
                                                                                                    { text: '开源模型 Llama / Mistral', link: '/01-models/open-source' },
                                                                                                    { text: '模型对比与选型', link: '/01-models/compare' }
                                                                                                  ]
                                                                                                },
                                                                                                {
                                                                                                  text: '🔧 AI 编程工具', items: [
                                                                                                    { text: 'Claude Code / OpenCode', link: '/02-coding-tools/claude-code' },
                                                                                                    { text: 'Cursor IDE', link: '/02-coding-tools/cursor' },
                                                                                                    { text: 'GitHub Copilot', link: '/02-coding-tools/copilot' },
                                                                                                    { text: 'Continue / Cody', link: '/02-coding-tools/continue-cody' },
                                                                                                    { text: 'Aider', link: '/02-coding-tools/aider' },
                                                                                                    { text: '命令行速查', link: '/02-coding-tools/commands' }
                                                                                                  ]
                                                                                                },
                                                                                                {
                                                                                                  text: '📦 SDK 接入', items: [
                                                                                                    { text: 'Claude SDK / Anthropic', link: '/03-sdks/claude-sdk' },
                                                                                                    { text: 'OpenAI SDK', link: '/03-sdks/openai-sdk' },
                                                                                                    { text: 'Gemini / Vertex AI SDK', link: '/03-sdks/gemini-sdk' },
                                                                                                    { text: 'LangChain', link: '/03-sdks/langchain' },
                                                                                                    { text: 'LlamaIndex', link: '/03-sdks/llamaindex' }
                                                                                                  ]
                                                                                                },
                                                                                                {
                                                                                                  text: '🏗️ Agent 框架', items: [
                                                                                                    { text: 'LangGraph', link: '/04-agents/langgraph' },
                                                                                                    { text: 'CrewAI', link: '/04-agents/crewai' },
                                                                                                    { text: 'AutoGen / Semantic Kernel', link: '/04-agents/autogen' },
                                                                                                    { text: 'Dify / Coze', link: '/04-agents/dify-coze' }
                                                                                                  ]
                                                                                                },
                                                                                                {
                                                                                                  text: '🔍 RAG 架构', items: [
                                                                                                    { text: 'RAG 模式详解', link: '/05-rag/patterns' },
                                                                                                    { text: '向量数据库', link: '/05-rag/vector-db' },
                                                                                                    { text: '嵌入模型 Embedding', link: '/05-rag/embedding' }
                                                                                                  ]
                                                                                                },
                                                                                                {
                                                                                                  text: '🔌 MCP 协议', items: [
                                                                                                    { text: 'MCP 核心概念', link: '/06-mcp/core' },
                                                                                                    { text: 'MCP Server / Client 开发', link: '/06-mcp/dev' },
                                                                                                    { text: 'Codex MCP 集成', link: '/06-mcp/codex-integration' }
                                                                                                  ]
                                                                                                },
                                                                                                {
                                                                                                  text: '📝 Prompt 工程', items: [
                                                                                                    { text: 'Chain-of-Thought', link: '/07-prompt/cot' },
                                                                                                    { text: '结构化 Prompt', link: '/07-prompt/structured' },
                                                                                                    { text: 'Few-shot / Multi-shot', link: '/07-prompt/few-shot' }
                                                                                                  ]
                                                                                                },
                                                                                                {
                                                                                                  text: '🎯 微调与训练', items: [
                                                                                                    { text: 'LoRA / QLoRA', link: '/08-finetuning/lora' },
                                                                                                    { text: '全量微调', link: '/08-finetuning/full' },
                                                                                                    { text: '数据准备', link: '/08-finetuning/data' },
                                                                                                    { text: '量化 GGUF / GPTQ', link: '/08-finetuning/quantization' }
                                                                                                  ]
                                                                                                },
                                                                                                {
                                                                                                  text: '📊 评测与质量', items: [
                                                                                                    { text: 'Eval 框架', link: '/09-eval/frameworks' },
                                                                                                    { text: 'Benchmark 与指标', link: '/09-eval/benchmark' },
                                                                                                    { text: 'RLHF / DPO', link: '/09-eval/alignment' }
                                                                                                  ]
                                                                                                },
                                                                                                {
                                                                                                  text: '🏗️ 部署与推理', items: [
                                                                                                    { text: 'Ollama 本地推理', link: '/10-deploy/ollama' },
                                                                                                    { text: 'vLLM / TGI 服务', link: '/10-deploy/vllm-tgi' },
                                                                                                    { text: 'API 托管', link: '/10-deploy/hosted' },
                                                                                                    { text: '🧬 DeepSeek Harness', link: '/10-deploy/deepseek-harness/00-overview' },
                                                                                                    { text: '  ├ 📘 使用文档', link: '/10-deploy/deepseek-harness/01-quickstart' },
                                                                                                    { text: '  ├ 📙 使用教程', link: '/10-deploy/deepseek-harness/02-tutorial' },
                                                                                                    { text: '  ├ 🎯 实战教程', link: '/10-deploy/deepseek-harness/03-recipes' },
                                                                                                    { text: '  ├ 🧩 常用插件', link: '/10-deploy/deepseek-harness/04-plugins' },
                                                                                                    { text: '  └ 🏛️ 经典架构', link: '/10-deploy/deepseek-harness/05-architecture' },
                                                                                                    { text: '🧠 Agent 高级实战', link: '/10-deploy/deepseek-harness/06-advanced' },
                                                                                                    { text: '  ├ 🧩 自定义工具', link: '/10-deploy/deepseek-harness/06-advanced#第-1 章自定义工具定义' },
                                                                                                    { text: '  ├ 🎯 意图识别', link: '/10-deploy/deepseek-harness/06-advanced#第-2 章意图识别' },
                                                                                                    { text: '  ├ 🤖 单 Agent 构建', link: '/10-deploy/deepseek-harness/06-advanced#第-3 章单-agent-智能体构建' },
                                                                                                    { text: '  ├ 👥 多 Agent 协作', link: '/10-deploy/deepseek-harness/06-advanced#第-4 章多-agent-协作' },
                                                                                                    { text: '  ├ 🔌 MCP 接入', link: '/10-deploy/deepseek-harness/06-advanced#第-5-章mcp-接入' },
                                                                                                    { text: '  ├ 🎓 Skill 系统', link: '/10-deploy/deepseek-harness/06-advanced#第-6-章skill-系统深度使用' },
                                                                                                    { text: '  ├ 📚 RAG 接入', link: '/10-deploy/deepseek-harness/06-advanced#第-7-章rag-接入' },
                                                                                                    { text: '  ├ 🛠️ 工具定义', link: '/10-deploy/deepseek-harness/06-advanced#第-8-章工具定义最佳实践' },
                                                                                                    { text: '  ├ 🧪 测试', link: '/10-deploy/deepseek-harness/06-advanced#第-9-章测试-agent--skill--tool' },
                                                                                                    { text: '  └ 🎁 完整实战', link: '/10-deploy/deepseek-harness/06-advanced#第-10-章完整实战项目' },
                                                                                                    { text: '⚙️ 运行时原理', link: '/10-deploy/deepseek-harness/07-runtime' },
                                                                                                    { text: '  ├ 🏛️ 架构总览', link: '/10-deploy/deepseek-harness/07-runtime#🏛️-运行时架构总览' },
                                                                                                    { text: '  ├ 🚀 启动流程', link: '/10-deploy/deepseek-harness/07-runtime#🚀-启动流程从-npx-dsh-web-到可用' },
                                                                                                    { text: '  ├ 🔄 Agent Loop', link: '/10-deploy/deepseek-harness/07-runtime#🔄-agent-loop-执行模型核心中的核心' },
                                                                                                    { text: '  ├ 🧰 工具调度', link: '/10-deploy/deepseek-harness/07-runtime#🧰-工具调度机制' },
                                                                                                    { text: '  ├ 👥 子代理', link: '/10-deploy/deepseek-harness/07-runtime#👥-子代理subagent机制' },
                                                                                                    { text: '  ├ 📡 消息流', link: '/10-deploy/deepseek-harness/07-runtime#📡-消息流web-ui-实时推送' },
                                                                                                    { text: '  ├ 🔒 沙箱权限', link: '/10-deploy/deepseek-harness/07-runtime#🔒-沙箱与权限检查' },
                                                                                                    { text: '  ├ 💾 状态管理', link: '/10-deploy/deepseek-harness/07-runtime#💾-状态管理' },
                                                                                                    { text: '  ├ 🧬 进程模型', link: '/10-deploy/deepseek-harness/07-runtime#🧬-进程模型' },
                                                                                                    { text: '  ├ 🛟 错误恢复', link: '/10-deploy/deepseek-harness/07-runtime#🛟-错误恢复' },
                                                                                                    { text: '  ├ 🆚 对比', link: '/10-deploy/deepseek-harness/07-runtime#🆚-与-claude-code-的本质区别' },
                                                                                                    { text: '  └ 🧪 调试技巧', link: '/10-deploy/deepseek-harness/07-runtime#🧪-调试与诊断技巧' },
                                                                                                    { text: '🔬 源码级深度', link: '/10-deploy/deepseek-harness/08-deep-dive' },
                                                                                                    { text: '  ├ 🔄 Agent Loop', link: '/10-deploy/deepseek-harness/08-deep-dive#1-agent-loop-主循环源码逐行分析' },
                                                                                                    { text: '  ├ 🏛️ Cordis', link: '/10-deploy/deepseek-harness/08-deep-dive#2-cordis-容器原理' },
                                                                                                    { text: '  ├ 🧰 Dispatcher', link: '/10-deploy/deepseek-harness/08-deep-dive#3-tool-dispatcher-调度机制' },
                                                                                                    { text: '  ├ 🔌 MCP', link: '/10-deploy/deepseek-harness/08-deep-dive#4-mcp-桥接实现' },
                                                                                                    { text: '  ├ 📡 流式', link: '/10-deploy/deepseek-harness/08-deep-dive#5-流式响应实现-sse--websocket' },
                                                                                                    { text: '  ├ 💾 持久化', link: '/10-deploy/deepseek-harness/08-deep-dive#6-会话持久化原理' },
                                                                                                    { text: '  ├ 📊 性能', link: '/10-deploy/deepseek-harness/08-deep-dive#7-性能基准' },
                                                                                                    { text: '  └ 🛟 排查', link: '/10-deploy/deepseek-harness/08-deep-dive#8-故障排查指南' },
                                                                                                    { text: '🏢 企业级 Agent', link: '/10-deploy/deepseek-harness/09-enterprise-agent' },
                                                                                                    { text: '  ├ 🎯 核心特征', link: '/10-deploy/deepseek-harness/09-enterprise-agent#🎯-企业级-agent-的核心特征' },
                                                                                                    { text: '  ├ 🏛️ 架构', link: '/10-deploy/deepseek-harness/09-enterprise-agent#🏛️-完整架构五件套' },
                                                                                                    { text: '  ├ 📁 目录', link: '/10-deploy/deepseek-harness/09-enterprise-agent#📁-完整目录结构' },
                                                                                                    { text: '  ├ 📋 preset', link: '/10-deploy/deepseek-harness/09-enterprise-agent#📋-1-presetyaml主配置' },
                                                                                                    { text: '  ├ 📚 Skills', link: '/10-deploy/deepseek-harness/09-enterprise-agent#📚-2-skills任务命令' },
                                                                                                    { text: '  ├ 🔌 Plugins', link: '/10-deploy/deepseek-harness/09-enterprise-agent#🔌-3-自定义-plugins' },
                                                                                                    { text: '  ├ 🤖 子代理', link: '/10-deploy/deepseek-harness/09-enterprise-agent#🤖-4-子代理多-agent-协作' },
                                                                                                    { text: '  ├ 🌐 MCP', link: '/10-deploy/deepseek-harness/09-enterprise-agent#🌐-5-mcp-配置' },
                                                                                                    { text: '  ├ 🚀 启动', link: '/10-deploy/deepseek-harness/09-enterprise-agent#🚀-6-启动' },
                                                                                                    { text: '  ├ 🐳 Docker', link: '/10-deploy/deepseek-harness/09-enterprise-agent#🐳-7-docker-部署' },
                                                                                                    { text: '  ├ 📦 分发', link: '/10-deploy/deepseek-harness/09-enterprise-agent#📦-8-分发给团队' },
                                                                                                    { text: '  ├ 📊 监控', link: '/10-deploy/deepseek-harness/09-enterprise-agent#📊-9-监控与运维' },
                                                                                                    { text: '  ├ 🧪 测试', link: '/10-deploy/deepseek-harness/09-enterprise-agent#🧪-10-测试' },
                                                                                                    { text: '  ├ 📖 README', link: '/10-deploy/deepseek-harness/09-enterprise-agent#📖-11-团队-readme-模板' },
                                                                                                    { text: '  └ 🎯 场景', link: '/10-deploy/deepseek-harness/09-enterprise-agent#🎯-12-其他场景模板速查' }
                                                                                                  ]
                                                                                                },
                                                                                                {
                                                                                                  text: '📡 工具调用', items: [
                                                                                                    { text: 'Function Calling', link: '/11-tools/function-calling' },
                                                                                                    { text: 'Tool Use 模式', link: '/11-tools/tool-use' },
                                                                                                    { text: 'Structured Output', link: '/11-tools/structured-output' }
                                                                                                  ]
                                                                                                },
                                                                                                {
                                                                                                  text: '🛠️ 安装与环境', items: [
                                                                                                    { text: 'pip / brew / npm 安装', link: '/12-install/package-managers' },
                                                                                                    { text: 'Docker 一键部署', link: '/12-install/docker' },
                                                                                                    { text: 'CUDA / GPU 环境', link: '/12-install/cuda-gpu' }
                                                                                                  ]
                                                                                                },
                                                                                                {
                                                                                                  text: '🔒 安全与治理', items: [
                                                                                                    { text: 'API Key 管理', link: '/13-security/api-keys' },
                                                                                                    { text: 'Guardrails / Content Safety', link: '/13-security/guardrails' },
                                                                                                    { text: '成本控制 / Token', link: '/13-security/cost' }
                                                                                                  ]
                                                                                                },
                                                                                                {
                                                                                                  text: '🎯 面试与学习', items: [
                                                                                                    { text: '高频面试题', link: '/14-interview/questions' },
                                                                                                    { text: '项目案例', link: '/14-interview/cases' },
                                                                                                    { text: '学习路径', link: '/14-interview/path' }
                                                                                                  ]
                                                                                                }
                                                                                              ],
                                                                                              '/graph': [{ text: '🌐 知识图谱', items: [{ text: '全局知识图谱', link: '/graph' }] }],
                                                                                              '/mindmap': [{ text: '🧭 思维导图', items: [{ text: 'AI 思维导图', link: '/mindmap' }] }],
                                                                                              '/cheatsheet': [{ text: '📋 命令速查', items: [{ text: 'AI 工具命令速查', link: '/cheatsheet' }] }],
                                                                                              '/path': [{ text: '🎯 学习路径', items: [{ text: 'AI 工程学习路径', link: '/path' }] }]
    },

    socialLinks: [{ icon: 'github', link: 'https://github.com' }],

    outline: { level: [2, 3], label: '页面大纲' },
    docFooter: { prev: '上一篇', next: '下一篇' },
    search: { provider: 'local' },

    footer: {
      message: 'AI 工程全栈 - 工具 / 大模型 / SDK / Agent · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>',
      copyright: 'MIT License'
    },
  }
})
