export const graphData = {
  nodes: [
    { name: 'JMM 内存模型', category: 'concurrency', link: '/01-concurrency-theory/jmm', value: 7 },
    { name: 'happens-before', category: 'concurrency', link: '/01-concurrency-theory/happens-before', value: 6 },
    { name: 'CAS / Lock-Free', category: 'concurrency', link: '/01-concurrency-theory/cas', value: 6 },
    { name: 'volatile / final', category: 'concurrency', link: '/01-concurrency-theory/volatile', value: 6 },
    { name: 'ThreadPoolExecutor', category: 'threadpool', link: '/02-thread-pool/executor', value: 6 },
    { name: 'ForkJoinPool', category: 'threadpool', link: '/02-thread-pool/forkjoin', value: 5 },
    { name: '虚拟线程 (JDK 21)', category: 'threadpool', link: '/02-thread-pool/virtual', value: 5 },
    { name: 'CAP 定理', category: 'ha', link: '/03-ha-theory/cap', value: 8 },
    { name: 'BASE / 最终一致性', category: 'ha', link: '/03-ha-theory/base', value: 6 },
    { name: 'Raft 共识', category: 'ha', link: '/03-ha-theory/raft', value: 6 },
    { name: 'Quorum 多数派', category: 'ha', link: '/03-ha-theory/quorum', value: 5 },
    { name: '幂等性设计', category: 'ha', link: '/03-ha-theory/idempotency', value: 6 },
    { name: '令牌桶算法', category: 'ratelimit', link: '/04-rate-limit/token-bucket', value: 6 },
    { name: '漏桶 / 滑动窗口', category: 'ratelimit', link: '/04-rate-limit/leaky-bucket', value: 5 },
    { name: '分布式限流', category: 'ratelimit', link: '/04-rate-limit/distributed', value: 6 },
    { name: '熔断器三态', category: 'circuit', link: '/05-circuit-breaker/states', value: 6 },
    { name: 'Sentinel / Hystrix', category: 'circuit', link: '/05-circuit-breaker/impl', value: 5 },
    { name: 'Fallback 设计', category: 'circuit', link: '/05-circuit-breaker/fallback', value: 5 },
    { name: '服务拆分原则', category: 'microservice', link: '/06-microservice/split', value: 6 },
    { name: '服务发现', category: 'microservice', link: '/06-microservice/discovery', value: 6 },
    { name: 'API 网关', category: 'microservice', link: '/06-microservice/gateway', value: 6 },
    { name: '配置中心', category: 'microservice', link: '/06-microservice/config', value: 5 },
    { name: '2PC / 3PC', category: 'disttx', link: '/07-distributed-tx/2pc', value: 6 },
    { name: 'TCC 模式', category: 'disttx', link: '/07-distributed-tx/tcc', value: 6 },
    { name: 'Saga 模式', category: 'disttx', link: '/07-distributed-tx/saga', value: 6 },
    { name: '本地消息表', category: 'disttx', link: '/07-distributed-tx/local-table', value: 5 },
    { name: 'Kafka vs RabbitMQ', category: 'mq', link: '/08-message-queue/compare', value: 6 },
    { name: '顺序 / 幂等', category: 'mq', link: '/08-message-queue/idempotency', value: 6 },
    { name: '死信 / 重试', category: 'mq', link: '/08-message-queue/dlq', value: 5 },
    { name: '多级缓存架构', category: 'cache', link: '/09-cache/architecture', value: 6 },
    { name: '缓存三大问题', category: 'cache', link: '/09-cache/breakdown', value: 6 },
    { name: '一致性策略', category: 'cache', link: '/09-cache/consistency', value: 5 },
    { name: '水平 / 垂直拆分', category: 'shard', link: '/10-database-sharding/strategy', value: 6 },
    { name: '路由 / 扩容', category: 'shard', link: '/10-database-sharding/routing', value: 5 },
    { name: '分布式 ID', category: 'shard', link: '/10-database-sharding/id', value: 6 },
    { name: '聚合 / 实体 / 值对象', category: 'ddd', link: '/11-ddd/basics', value: 6 },
    { name: '限界上下文', category: 'ddd', link: '/11-ddd/bounded-context', value: 6 },
    { name: '事件风暴', category: 'ddd', link: '/11-ddd/event-storming', value: 5 },
    { name: 'Service Mesh', category: 'patterns', link: '/12-microservice-patterns/service-mesh', value: 6 },
    { name: 'Sidecar', category: 'patterns', link: '/12-microservice-patterns/sidecar', value: 5 },
    { name: 'Saga / Bulkhead', category: 'patterns', link: '/12-microservice-patterns/saga', value: 5 },
    { name: 'Metrics/Tracing/Logging', category: 'observability', link: '/13-observability/three-pillars', value: 6 },
    { name: 'OpenTelemetry', category: 'observability', link: '/13-observability/otel', value: 5 },
    { name: '秒杀系统', category: 'cases', link: '/14-enterprise-cases/flash-sale', value: 7 },
    { name: '短链系统', category: 'cases', link: '/14-enterprise-cases/short-url', value: 5 },
    { name: '异地多活', category: 'cases', link: '/14-enterprise-cases/multi-region', value: 6 }
  ],
  links: [
    { source: 'JMM 内存模型', target: 'happens-before' },
    { source: 'happens-before', target: 'volatile / final' },
    { source: 'CAS / Lock-Free', target: 'volatile / final' },
    { source: 'volatile / final', target: 'ThreadPoolExecutor' },
    { source: 'ThreadPoolExecutor', target: 'ForkJoinPool' },
    { source: 'ThreadPoolExecutor', target: '虚拟线程 (JDK 21)' },
    { source: 'ForkJoinPool', target: '虚拟线程 (JDK 21)' },
    { source: 'CAP 定理', target: 'BASE / 最终一致性' },
    { source: 'CAP 定理', target: 'Raft 共识' },
    { source: 'Raft 共识', target: 'Quorum 多数派' },
    { source: 'CAP 定理', target: '幂等性设计' },
    { source: '幂等性设计', target: '令牌桶算法' },
    { source: 'Base / 最终一致性', target: '分布式限流' },
    { source: 'Quorum 多数派', target: 'Raft 共识' },
    { source: '令牌桶算法', target: '漏桶 / 滑动窗口' },
    { source: '分布式限流', target: '熔断器三态' },
    { source: '熔断器三态', target: 'Fallback 设计' },
    { source: 'Fallback 设计', target: 'Sentinel / Hystrix' },
    { source: 'Sentinel / Hystrix', target: 'API 网关' },
    { source: '服务拆分原则', target: '服务发现' },
    { source: '服务发现', target: 'API 网关' },
    { source: 'API 网关', target: '配置中心' },
    { source: 'API 网关', target: 'Service Mesh' },
    { source: '2PC / 3PC', target: 'TCC 模式' },
    { source: 'TCC 模式', target: 'Saga 模式' },
    { source: 'Saga 模式', target: '本地消息表' },
    { source: 'Saga 模式', target: 'Kafka vs RabbitMQ' },
    { source: 'Kafka vs RabbitMQ', target: '顺序 / 幂等' },
    { source: '顺序 / 幂等', target: '死信 / 重试' },
    { source: '本地消息表', target: 'Kafka vs RabbitMQ' },
    { source: '多级缓存架构', target: '一致性策略' },
    { source: '一致性策略', target: '缓存三大问题' },
    { source: '水平 / 垂直拆分', target: '路由 / 扩容' },
    { source: '路由 / 扩容', target: '分布式 ID' },
    { source: '聚合 / 实体 / 值对象', target: '限界上下文' },
    { source: '限界上下文', target: '事件风暴' },
    { source: '事件风暴', target: 'Saga / Bulkhead' },
    { source: 'Service Mesh', target: 'Sidecar' },
    { source: 'Service Mesh', target: 'Saga / Bulkhead' },
    { source: 'Metrics/Tracing/Logging', target: 'OpenTelemetry' },
    { source: 'OpenTelemetry', target: '服务拆分原则' },
    { source: '秒杀系统', target: '多级缓存架构' },
    { source: '秒杀系统', target: '本地消息表' },
    { source: '秒杀系统', target: '路由 / 扩容' },
    { source: '短链系统', target: '一致性策略' },
    { source: '异地多活', target: 'Quorum 多数派' },
    { source: '异地多活', target: 'BASE / 最终一致性' }
  ]
}