export const graphData = {
  nodes: [
    { name: 'OOP 类与对象', category: 'basics', link: '/01-basics/oop', value: 6 },
    { name: '数据类型/包装类', category: 'basics', link: '/01-basics/datatypes', value: 5 },
    { name: '异常处理', category: 'basics', link: '/01-basics/exceptions', value: 5 },
    { name: '泛型/注解/反射', category: 'basics', link: '/01-basics/generics', value: 6 },
    { name: 'JDK 17-21 新特性', category: 'basics', link: '/01-basics/new-features', value: 5 },
    { name: 'ArrayList/LinkedList', category: 'collections', link: '/02-collections/list', value: 6 },
    { name: 'HashMap 原理', category: 'collections', link: '/02-collections/map', value: 7 },
    { name: 'TreeSet/HashSet', category: 'collections', link: '/02-collections/set', value: 5 },
    { name: 'Stream API', category: 'collections', link: '/02-collections/stream', value: 6 },
    { name: '并发集合', category: 'collections', link: '/02-collections/concurrent', value: 5 },
    { name: '线程/线程池', category: 'concurrency', link: '/03-concurrency/thread-pool', value: 7 },
    { name: 'synchronized/AQS', category: 'concurrency', link: '/03-concurrency/locks', value: 7 },
    { name: 'JUC 工具', category: 'concurrency', link: '/03-concurrency/juc', value: 6 },
    { name: 'CompletableFuture', category: 'concurrency', link: '/03-concurrency/future', value: 6 },
    { name: '虚拟线程 Loom', category: 'concurrency', link: '/03-concurrency/virtual-threads', value: 5 },
    { name: 'JVM 运行时数据区', category: 'jvm', link: '/04-jvm/runtime', value: 7 },
    { name: '类加载机制', category: 'jvm', link: '/04-jvm/classloading', value: 6 },
    { name: '字节码/指令', category: 'jvm', link: '/04-jvm/bytecode', value: 5 },
    { name: 'OOM 排查', category: 'jvm', link: '/04-jvm/oom', value: 5 },
    { name: 'GC 算法', category: 'gc', link: '/05-gc/algorithms', value: 6 },
    { name: 'G1/ZGC/Shenandoah', category: 'gc', link: '/05-gc/collectors', value: 7 },
    { name: 'GC 调优', category: 'gc', link: '/05-gc/tuning', value: 6 },
    { name: 'IoC/DI/AOP', category: 'spring', link: '/06-spring/ioc-aop', value: 7 },
    { name: 'Spring Boot 自动配置', category: 'spring', link: '/06-spring/boot', value: 7 },
    { name: 'Spring MVC', category: 'spring', link: '/06-spring/mvc', value: 6 },
    { name: '声明式事务', category: 'spring', link: '/06-spring/transaction', value: 6 },
    { name: 'Nacos 注册/配置', category: 'springcloud', link: '/07-spring-cloud/nacos', value: 6 },
    { name: 'Gateway/Sentinel', category: 'springcloud', link: '/07-spring-cloud/gateway', value: 6 },
    { name: 'Seata 分布式事务', category: 'springcloud', link: '/07-spring-cloud/seata', value: 5 },
    { name: 'JDBC/HikariCP', category: 'database', link: '/08-database/jdbc', value: 5 },
    { name: 'MyBatis/Plus', category: 'database', link: '/08-database/mybatis', value: 6 },
    { name: 'JPA/Hibernate', category: 'database', link: '/08-database/jpa', value: 5 },
    { name: 'BIO/NIO/AIO', category: 'io', link: '/09-io/nio', value: 6 },
    { name: 'Netty 框架', category: 'io', link: '/09-io/netty', value: 6 },
    { name: '序列化/JSON/ProtoBuf', category: 'io', link: '/09-io/serialize', value: 5 },
    { name: 'JVM 调优参数', category: 'performance', link: '/10-performance/jvm-tuning', value: 6 },
    { name: 'Arthas 诊断', category: 'performance', link: '/10-performance/arthas', value: 6 },
    { name: 'jstack/jmap/jstat', category: 'performance', link: '/10-performance/jvm-tools', value: 6 },
    { name: '创建型模式', category: 'design', link: '/11-design/creational', value: 5 },
    { name: '结构型模式', category: 'design', link: '/11-design/structural', value: 5 },
    { name: '行为型模式', category: 'design', link: '/11-design/behavioral', value: 5 },
    { name: 'Maven/Gradle', category: 'tools', link: '/12-tools/build', value: 6 },
    { name: 'Lombok/MapStruct', category: 'tools', link: '/12-tools/lombok', value: 5 },
    { name: '常用命令', category: 'tools', link: '/12-tools/commands', value: 5 },
    { name: 'JUnit5', category: 'testing', link: '/13-testing/junit5', value: 5 },
    { name: 'Mockito', category: 'testing', link: '/13-testing/mockito', value: 5 },
    { name: 'Spring Boot Test', category: 'testing', link: '/13-testing/spring-test', value: 5 },
    { name: '高频面试题', category: 'interview', link: '/14-interview/questions', value: 5 },
    { name: '手写代码', category: 'interview', link: '/14-interview/coding', value: 5 },
    { name: '学习路径', category: 'interview', link: '/14-interview/path', value: 4 }
  ],
  links: [
    { source: 'OOP 类与对象', target: 'ArrayList/LinkedList' },
    { source: 'OOP 类与对象', target: 'IoC/DI/AOP' },
    { source: '数据类型/包装类', target: 'HashMap 原理' },
    { source: '异常处理', target: 'Spring Boot 自动配置' },
    { source: '泛型/注解/反射', target: 'IoC/DI/AOP' },
    { source: '泛型/注解/反射', target: 'MyBatis/Plus' },
    { source: 'JDK 17-21 新特性', target: '虚拟线程 Loom' },
    { source: 'JDK 17-21 新特性', target: 'Stream API' },
    { source: 'ArrayList/LinkedList', target: 'Stream API' },
    { source: 'ArrayList/LinkedList', target: '并发集合' },
    { source: 'HashMap 原理', target: '并发集合' },
    { source: 'HashMap 原理', target: 'TreeSet/HashSet' },
    { source: 'Stream API', target: 'OOP 类与对象' },
    { source: '线程/线程池', target: 'JUC 工具' },
    { source: '线程/线程池', target: 'CompletableFuture' },
    { source: 'synchronized/AQS', target: 'JUC 工具' },
    { source: 'synchronized/AQS', target: '线程/线程池' },
    { source: 'JUC 工具', target: '并发集合' },
    { source: 'CompletableFuture', target: '虚拟线程 Loom' },
    { source: 'JVM 运行时数据区', target: 'GC 算法' },
    { source: 'JVM 运行时数据区', target: 'OOM 排查' },
    { source: '类加载机制', target: 'IoC/DI/AOP' },
    { source: '类加载机制', target: '字节码/指令' },
    { source: '字节码/指令', target: 'JDK 17-21 新特性' },
    { source: 'GC 算法', target: 'G1/ZGC/Shenandoah' },
    { source: 'GC 算法', target: 'GC 调优' },
    { source: 'G1/ZGC/Shenandoah', target: 'JVM 调优参数' },
    { source: 'GC 调优', target: 'JVM 调优参数' },
    { source: 'IoC/DI/AOP', target: 'Spring Boot 自动配置' },
    { source: 'IoC/DI/AOP', target: 'Spring MVC' },
    { source: 'IoC/DI/AOP', target: '声明式事务' },
    { source: 'Spring Boot 自动配置', target: 'Nacos 注册/配置' },
    { source: 'Spring MVC', target: 'Gateway/Sentinel' },
    { source: '声明式事务', target: 'Seata 分布式事务' },
    { source: 'Nacos 注册/配置', target: 'Gateway/Sentinel' },
    { source: 'Gateway/Sentinel', target: 'Seata 分布式事务' },
    { source: 'JDBC/HikariCP', target: 'MyBatis/Plus' },
    { source: 'JDBC/HikariCP', target: 'JPA/Hibernate' },
    { source: 'MyBatis/Plus', target: 'Spring Boot 自动配置' },
    { source: 'BIO/NIO/AIO', target: 'Netty 框架' },
    { source: 'BIO/NIO/AIO', target: 'CompletableFuture' },
    { source: 'Netty 框架', target: 'Spring MVC' },
    { source: '序列化/JSON/ProtoBuf', target: 'Spring MVC' },
    { source: 'JVM 调优参数', target: 'jstack/jmap/jstat' },
    { source: 'JVM 调优参数', target: 'Arthas 诊断' },
    { source: 'Arthas 诊断', target: 'OOM 排查' },
    { source: 'jstack/jmap/jstat', target: '线程/线程池' },
    { source: '创建型模式', target: 'IoC/DI/AOP' },
    { source: '结构型模式', target: 'Spring MVC' },
    { source: '行为型模式', target: '声明式事务' },
    { source: 'Maven/Gradle', target: 'Spring Boot 自动配置' },
    { source: 'Lombok/MapStruct', target: 'OOP 类与对象' },
    { source: 'JUnit5', target: 'Spring Boot 自动配置' },
    { source: 'JUnit5', target: 'Mockito' },
    { source: 'Mockito', target: 'Spring Boot Test' },
    { source: 'JUnit5', target: '常用命令' },
    { source: '高频面试题', target: 'HashMap 原理' },
    { source: '高频面试题', target: 'synchronized/AQS' },
    { source: '手写代码', target: '创建型模式' },
    { source: '手写代码', target: 'Stream API' }
  ]
}