// Big data knowledge graph
export const graphData = {
  nodes: [
    { name: '大数据 4V', category: 'basics', link: '/01-basics/4v', value: 6 },
    { name: 'Hadoop 生态', category: 'basics', link: '/01-basics/hadoop-eco', value: 6 },
    { name: '批 / 流计算', category: 'basics', link: '/01-basics/batch-stream', value: 6 },
    { name: 'CAP 定理', category: 'basics', link: '/01-basics/cap', value: 6 },
    { name: 'HDFS 架构', category: 'hdfs', link: '/02-hdfs/architecture', value: 7 },
    { name: '副本机制', category: 'hdfs', link: '/02-hdfs/replication', value: 5 },
    { name: 'NameNode HA', category: 'hdfs', link: '/02-hdfs/ha', value: 5 },
    { name: 'HDFS 命令', category: 'hdfs', link: '/02-hdfs/commands', value: 5 },
    { name: 'MapReduce 原理', category: 'mapreduce', link: '/03-mapreduce/principle', value: 6 },
    { name: 'Shuffle 详解', category: 'mapreduce', link: '/03-mapreduce/shuffle', value: 6 },
    { name: 'Combiner 与 Partitioner', category: 'mapreduce', link: '/03-mapreduce/optimize', value: 5 },
    { name: 'Spark Core / RDD', category: 'spark', link: '/04-spark/rdd', value: 7 },
    { name: 'Spark SQL / DataFrame', category: 'spark', link: '/04-spark/dataframe', value: 7 },
    { name: 'Spark Structured Streaming', category: 'spark', link: '/04-spark/streaming', value: 6 },
    { name: 'Spark 调优', category: 'spark', link: '/04-spark/tuning', value: 6 },
    { name: 'Flink 架构', category: 'flink', link: '/05-flink/architecture', value: 6 },
    { name: 'Flink 状态与 Checkpoint', category: 'flink', link: '/05-flink/state', value: 6 },
    { name: 'Exactly-once 语义', category: 'flink', link: '/05-flink/exactly-once', value: 6 },
    { name: 'Hive 架构', category: 'hive', link: '/06-hive/architecture', value: 6 },
    { name: 'Hive 优化', category: 'hive', link: '/06-hive/optimize', value: 5 },
    { name: 'Hive on Spark / Tez', category: 'hive', link: '/06-hive/engine', value: 5 },
    { name: 'Kafka Streams', category: 'kafka', link: '/07-kafka-streaming/streams', value: 6 },
    { name: 'Flink CDC', category: 'kafka', link: '/07-kafka-streaming/cdc', value: 6 },
    { name: 'OLAP vs OLTP', category: 'modeling', link: '/08-modeling/olap-oltp', value: 6 },
    { name: 'Inmon vs Kimball', category: 'modeling', link: '/08-modeling/inmon-kimball', value: 6 },
    { name: '维度建模 星型 / 雪花', category: 'modeling', link: '/08-modeling/star-snowflake', value: 6 },
    { name: 'Data Vault', category: 'modeling', link: '/08-modeling/data-vault', value: 5 },
    { name: 'Snowflake 架构', category: 'dwarch', link: '/09-dw-architecture/snowflake', value: 6 },
    { name: 'Redshift / BigQuery', category: 'dwarch', link: '/09-dw-architecture/redshift-bigquery', value: 5 },
    { name: '数据湖 三剑客', category: 'datalake', link: '/10-data-lake/three-pillars', value: 6 },
    { name: 'Delta Lake / Iceberg / Hudi', category: 'datalake', link: '/10-data-lake/delta-iceberg-hudi', value: 6 },
    { name: 'Lakehouse 架构', category: 'datalake', link: '/10-data-lake/lakehouse', value: 6 },
    { name: 'Airflow / dbt', category: 'elt', link: '/11-elt-pipeline/airflow-dbt', value: 6 },
    { name: 'CDC 同步', category: 'elt', link: '/11-elt-pipeline/cdc', value: 6 },
    { name: '数据血缘', category: 'elt', link: '/11-elt-pipeline/lineage', value: 5 },
    { name: 'ClickHouse 架构', category: 'olap', link: '/12-olap-engine/clickhouse', value: 6 },
    { name: 'Doris / StarRocks', category: 'olap', link: '/12-olap-engine/doris-starrocks', value: 5 },
    { name: 'OLAP 选型', category: 'olap', link: '/12-olap-engine/selection', value: 5 },
    { name: '用户画像案例', category: 'cases', link: '/13-cases/user-profile', value: 6 },
    { name: '推荐系统数据流', category: 'cases', link: '/13-cases/recommendation', value: 6 },
    { name: '风控实时特征', category: 'cases', link: '/13-cases/risk-control', value: 6 },
    { name: '日志分析平台', category: 'cases', link: '/13-cases/log-platform', value: 5 },
    { name: '高频面试题', category: 'interview', link: '/14-interview-practice/questions', value: 6 },
    { name: '项目案例', category: 'interview', link: '/14-interview-practice/cases', value: 5 }
  ],
  links: [
    { source: '大数据 4V', target: 'CAP 定理' },
    { source: '大数据 4V', target: '批 / 流计算' },
    { source: '大数据 4V', target: 'OLAP vs OLTP' },
    { source: 'Hadoop 生态', target: 'HDFS 架构' },
    { source: 'Hadoop 生态', target: 'MapReduce 原理' },
    { source: 'Hadoop 生态', target: 'Hive 架构' },
    { source: '批 / 流计算', target: 'Spark Structured Streaming' },
    { source: '批 / 流计算', target: 'Flink 架构' },
    { source: '批 / 流计算', target: 'Kafka Streams' },
    { source: 'HDFS 架构', target: '副本机制' },
    { source: 'HDFS 架构', target: 'NameNode HA' },
    { source: 'HDFS 架构', target: 'HDFS 命令' },
    { source: 'MapReduce 原理', target: 'Shuffle 详解' },
    { source: 'MapReduce 原理', target: 'Combiner 与 Partitioner' },
    { source: 'MapReduce 原理', target: 'Hive on Spark / Tez' },
    { source: 'Spark Core / RDD', target: 'Spark SQL / DataFrame' },
    { source: 'Spark Core / RDD', target: 'Spark Structured Streaming' },
    { source: 'Spark SQL / DataFrame', target: 'Spark 调优' },
    { source: 'Spark Structured Streaming', target: 'Flink 架构' },
    { source: 'Flink 架构', target: 'Flink 状态与 Checkpoint' },
    { source: 'Flink 架构', target: 'Exactly-once 语义' },
    { source: 'Flink 架构', target: 'Flink CDC' },
    { source: 'Hive 架构', target: 'Hive 优化' },
    { source: 'Hive 架构', target: 'Hive on Spark / Tez' },
    { source: 'Hive 优化', target: 'ClickHouse 架构' },
    { source: 'Kafka Streams', target: 'Flink CDC' },
    { source: 'Flink CDC', target: 'CDC 同步' },
    { source: 'OLAP vs OLTP', target: '数据湖 三剑客' },
    { source: 'OLAP vs OLTP', target: 'Inmon vs Kimball' },
    { source: '数据湖 三剑客', target: 'Delta Lake / Iceberg / Hudi' },
    { source: '数据湖 三剑客', target: 'Lakehouse 架构' },
    { source: 'Delta Lake / Iceberg / Hudi', target: 'Spark SQL / DataFrame' },
    { source: 'Lakehouse 架构', target: 'Iceberg / Hudi' },
    { source: 'Snowflake 架构', target: 'Redshift / BigQuery' },
    { source: 'Snowflake 架构', target: 'OLAP 选型' },
    { source: 'Inmon vs Kimball', target: '维度建模 星型 / 雪花' },
    { source: 'Inmon vs Kimball', target: 'Data Vault' },
    { source: '维度建模 星型 / 雪花', target: 'Hive 优化' },
    { source: 'Airflow / dbt', target: '数据血缘' },
    { source: 'CDC 同步', target: '数据血缘' },
    { source: 'Airflow / dbt', target: 'Flink CDC' },
    { source: 'ClickHouse 架构', target: 'OLAP 选型' },
    { source: 'Doris / StarRocks', target: 'OLAP 选型' },
    { source: 'Doris / StarRocks', target: 'Lakehouse 架构' },
    { source: '用户画像案例', target: '高性能标签画像' },
    { source: '用户画像案例', target: 'Hive 架构' },
    { source: '用户画像案例', target: 'Spark SQL / DataFrame' },
    { source: '推荐系统数据流', target: 'Kafka Streams' },
    { source: '推荐系统数据流', target: 'Flink 架构' },
    { source: '风控实时特征', target: 'Flink CDC' },
    { source: '日志分析平台', target: 'ClickHouse 架构' },
    { source: '日志分析平台', target: 'Kafka Streams' },
    { source: 'Data Vault', target: 'Inmon vs Kimball' }
  ]
}
