/**
 * @generated from shared-assets/vitepress-template/config.mts.tpl
 * DO NOT EDIT THIS FILE DIRECTLY — edit the template and re-run render-config.py
 *
 * 模板变量（render-config.py 替换）：
 *   clickhouse         e.g. "ai", "java", "clickhouse"
 *   /clickhouse/       e.g. "/ai/", "/clickhouse/"
 *   ClickHouse      e.g. "AI 工程全栈"
 *   OLAP 列式数据库深度图谱 - MergeTree / 主键索引 / 数据分区 / 向量化执行 / 实时数仓 · Kafka 引擎 / Grafana / Prometheus · vs Doris / StarRocks / TiDB / Snowflake · 6 大类 · 35 节点       e.g. "系统化学习 AI 工具..."
 *   #FFCC01     e.g. "#8b5cf6"
 *   zh-CN       e.g. "zh-CN"
 *   ClickHouse 是 Yandex 开源的高性能列式 OLAP 数据库 · <a href="https://clickhouse.com/" target="_blank">clickhouse.com</a> · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>  e.g. "AI 工程全栈 - 工具 / 大模型 / SDK / Agent"
 *   []   e.g. '[{ icon: "github", link: "https://github.com" }]'
 */
import { defineConfig } from 'vitepress'
import { fileURLToPath, URL } from 'node:url'

// P0: VitePress/rollup 默认 fs.allow 限制 cwd 外 import。用 vite alias 解决相对路径。
const SHARED_ASSETS = fileURLToPath(new URL('../../shared-assets', import.meta.url))

export default defineConfig({
  vite: {
    resolve: {
      alias: [
        { find: '@shared', replacement: SHARED_ASSETS },
      ],
    },
  },
  base: '/clickhouse/',
  title: 'ClickHouse',
  description: 'OLAP 列式数据库深度图谱 - MergeTree / 主键索引 / 数据分区 / 向量化执行 / 实时数仓 · Kafka 引擎 / Grafana / Prometheus · vs Doris / StarRocks / TiDB / Snowflake · 6 大类 · 35 节点',
  lang: 'zh-CN',
  lastUpdated: true,
  srcDir: 'docs',
  cleanUrls: true,
  ignoreDeadLinks: true,
  head: [
    ['meta', { name: 'viewport', content: 'width=device-width,initial-scale=1,viewport-fit=cover' }],
    ['meta', { name: 'theme-color', content: '#FFCC01' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:locale', content: 'zh_CN' }],
    ['meta', { property: 'og:site_name', content: 'ClickHouse' }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['link', { rel: 'icon', href: '/favicon.svg', type: 'image/svg+xml' }],
    ['link', { rel: 'icon', href: '/favicon.ico', type: 'image/x-icon' }],
    ['link', { rel: 'apple-touch-icon', href: '/apple-touch-icon.png', sizes: '180x180' }],
  ],
  themeConfig: {
    siteTitle: 'ClickHouse',

    // === 统一 nav（C1 规范：顶部 7 项 + 跨站 dropdown）===
    // 1) 门户  2) 首页  3) 知识图谱  4) 思维导图  5) 命令速查  6) 学习路径  7) 更多站点 ▼
    nav: [
      { text: '🏠 门户', link: 'https://java-px.bot.cd/', target: '_blank' },
      { text: '首页', link: '/' },
      { text: '知识图谱', link: '/graph' },
      { text: '思维导图', link: '/mindmap' },
      { text: '命令速查', link: '/cheatsheet' },
      { text: '学习路径', link: '/path' },
      {
        text: '更多站点',
        items: [
                  { text: "ElasticSearch", link: "https://java-px.bot.cd/es/" },
        { text: "MySQL", link: "https://java-px.bot.cd/mysql/" },
        { text: "Redis", link: "https://java-px.bot.cd/redis/" },
        { text: "微服务 / Spring Cloud", link: "https://java-px.bot.cd/cloud/" },
        { text: "Python", link: "https://java-px.bot.cd/python/" },
        { text: "Kafka", link: "https://java-px.bot.cd/kafka/" },
        { text: "Java Web 开发", link: "https://java-px.bot.cd/java/" },
        { text: "在线工具", link: "https://java-px.bot.cd/tools/" },
        { text: "前端 & Node", link: "https://java-px.bot.cd/frontend/" },
        { text: "Linux 服务器", link: "https://java-px.bot.cd/linux/" },
        { text: "云原生 / Docker / K8s", link: "https://java-px.bot.cd/cloud-native/" },
        { text: "AI 工具 / 大模型", link: "https://java-px.bot.cd/ai/" },
        { text: "大数据", link: "https://java-px.bot.cd/bigdata/" },
        { text: "计算机网络", link: "https://java-px.bot.cd/network/" },
        { text: "视频处理", link: "https://java-px.bot.cd/video/" },
        { text: "文件系统与存储", link: "https://java-px.bot.cd/filesystem/" },
        { text: "Java 语言", link: "https://java-px.bot.cd/java-language/" },
        { text: "企业级架构", link: "https://java-px.bot.cd/architecture/" },
        { text: "系统设计", link: "https://java-px.bot.cd/system-design/" },
        { text: "PostgreSQL", link: "https://java-px.bot.cd/postgresql/" },
        { text: "可观测性", link: "https://java-px.bot.cd/observability/" },
        { text: "安全", link: "https://java-px.bot.cd/security/" },
        { text: "DevOps", link: "https://java-px.bot.cd/devops/" },
        { text: "Rust", link: "https://java-px.bot.cd/rust/" },
        { text: "Go", link: "https://java-px.bot.cd/go/" },
        { text: "设计模式", link: "https://java-px.bot.cd/design-pattern/" },
        { text: "混沌工程", link: "https://java-px.bot.cd/chaos/" },
        { text: "物联网", link: "https://java-px.bot.cd/iot/" },
        { text: "安卓", link: "https://java-px.bot.cd/android/" },
        { text: "游戏开发", link: "https://java-px.bot.cd/game/" },
        ]
      }
    ],

    // === 各站独立 sidebar（render-config.py 保留原值）===
    sidebar: {
    
        
            
                              '/': [
                                {
                                  text: '🟡 ClickHouse 基础', collapsed: false, items: [
                                    { text: 'ClickHouse 总览', link: '/01-basics/overview' },
                                    { text: '历史与特点', link: '/01-basics/history' },
                                    { text: '安装部署', link: '/01-basics/installation' },
                                    { text: '客户端与连接', link: '/01-basics/client' },
                                    { text: '数据类型', link: '/01-basics/data-types' }
                                  ]
                                },
                                {
                                  text: '🔍 SQL 实战', collapsed: false, items: [
                                    { text: 'SQL 总览', link: '/02-sql/overview' },
                                    { text: 'SELECT 与聚合', link: '/02-sql/select-aggregate' },
                                    { text: 'JOIN 用法', link: '/02-sql/join' },
                                    { text: '常用函数', link: '/02-sql/functions' },
                                    { text: '窗口函数', link: '/02-sql/window-functions' },
                                    { text: '字典 Dictionary', link: '/02-sql/dictionary' }
                                  ]
                                },
                                {
                                  text: '⚙️ 表引擎', collapsed: false, items: [
                                    { text: '表引擎总览', link: '/03-table-engine/overview' },
                                    { text: 'MergeTree 家族', link: '/03-table-engine/mergetree-family' },
                                    { text: 'Log 引擎', link: '/03-table-engine/log-engine' },
                                    { text: 'Kafka 引擎', link: '/03-table-engine/kafka-engine' },
                                    { text: 'Distributed 表', link: '/03-table-engine/distributed' },
                                    { text: 'MaterializedView', link: '/03-table-engine/materialized-view' }
                                  ]
                                },
                                {
                                  text: '📊 OLAP 实战场景', collapsed: false, items: [
                                    { text: 'OLAP 场景总览', link: '/04-olap-scenarios/overview' },
                                    { text: '用户行为埋点', link: '/04-olap-scenarios/user-tracking' },
                                    { text: '日志分析', link: '/04-olap-scenarios/log-analysis' },
                                    { text: '指标存储', link: '/04-olap-scenarios/metrics-storage' },
                                    { text: '实时数仓', link: '/04-olap-scenarios/realtime-warehouse' },
                                    { text: 'Bitmap 去重', link: '/04-olap-scenarios/bitmap' }
                                  ]
                                },
                                {
                                  text: '🔌 生态工具链', collapsed: false, items: [
                                    { text: '生态总览', link: '/05-ecosystem/overview' },
                                    { text: 'Kafka 实时集成', link: '/05-ecosystem/kafka-integration' },
                                    { text: 'Grafana 可视化', link: '/05-ecosystem/grafana' },
                                    { text: 'Prometheus remote_write', link: '/05-ecosystem/prometheus' },
                                    { text: 'Go 客户端 ch-go', link: '/05-ecosystem/go-client' },
                                    { text: 'dbt + Airbyte 集成', link: '/05-ecosystem/dbt-airbyte' }
                                  ]
                                },
                                {
                                  text: '🆚 对比与选型', collapsed: false, items: [
                                    { text: '选型总览', link: '/06-compare/overview' },
                                    { text: 'vs MySQL / PostgreSQL', link: '/06-compare/vs-mysql-pg' },
                                    { text: 'vs Doris', link: '/06-compare/vs-doris' },
                                    { text: 'vs StarRocks', link: '/06-compare/vs-starrocks' },
                                    { text: 'vs TiDB', link: '/06-compare/vs-tidb' }
                                  ]
                                },
                                {
                                  text: '📖 大厂实战案例', collapsed: false, items: [
                                    { text: '12 个真实案例', link: '/case-study' }
                                  ]
                                }
                              ]
    },

    socialLinks: [],

    outline: { level: [2, 3], label: '页面大纲' },
    docFooter: { prev: '上一篇', next: '下一篇' },
    search: { provider: 'local' },

    footer: {
      message: 'ClickHouse 是 Yandex 开源的高性能列式 OLAP 数据库 · <a href="https://clickhouse.com/" target="_blank">clickhouse.com</a> · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>',
      copyright: 'MIT License'
    },
  }
})
