/**
 * @generated from shared-assets/vitepress-template/config.mts.tpl
 * DO NOT EDIT THIS FILE DIRECTLY — edit the template and re-run render.
 *
 * 模板变量（render-config.sh 替换）：
 *   @SITE_ID         e.g. "ai", "java", "clickhouse"
 *   @SITE_BASE       e.g. "/ai/", "/clickhouse/"
 *   @SITE_TITLE      e.g. "AI 工程全栈"
 *   @SITE_DESC       e.g. "系统化学习 AI 工具..."
 *   @SITE_ACCENT     e.g. "#8b5cf6"
 *   @SITE_LANG       e.g. "zh-CN"
 *   @FOOTER_MESSAGE  e.g. "AI 工程全栈 - 工具 / 大模型 / SDK / Agent"
 *   @SOCIAL_GITHUB   e.g. "https://github.com" or "" for none
 */
import { defineConfig } from 'vitepress'

export default defineConfig({
  base: '@SITE_BASE',
  title: '@SITE_TITLE',
  description: '@SITE_DESC',
  lang: '@SITE_LANG',
  lastUpdated: true,
  srcDir: 'docs',
  cleanUrls: true,
  ignoreDeadLinks: true,
  head: [
    ['meta', { name: 'viewport', content: 'width=device-width,initial-scale=1,viewport-fit=cover' }],
    ['meta', { name: 'theme-color', content: '@SITE_ACCENT' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:locale', content: 'zh_CN' }],
    ['meta', { property: 'og:site_name', content: '@SITE_TITLE' }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['link', { rel: 'icon', href: '/favicon.svg', type: 'image/svg+xml' }],
    ['link', { rel: 'icon', href: '/favicon.ico', type: 'image/x-icon' }],
    ['link', { rel: 'apple-touch-icon', href: '/apple-touch-icon.png', sizes: '180x180' }],
  ],
  themeConfig: {
    siteTitle: '@SITE_TITLE',

    // === 统一 nav（前 5 项：C1 规范）===
    // 1) 门户  2) 站内首页  3) 知识图谱  4) 命令速查  5) 学习路径
    // 各站可在后追加自定义项
    nav: [
      { text: '🏠 门户', link: 'https://java-px.bot.cd/', target: '_blank' },
      { text: '首页', link: '/' },
      // @NAV_EXTRA@  ← render 脚本插入此站自定义项
      {
        text: '更多站点',
        items: [
          // @CROSS_SITES@ ← render 脚本插入跨站链接（按 data-cat 分组）
        ]
      }
    ],

    // sidebar 由各站独立配置（render 脚本不动）
    // @SIDEBAR@

    socialLinks: @SOCIAL_GITHUB@,

    outline: { level: [2, 3], label: '页面大纲' },
    docFooter: { prev: '上一篇', next: '下一篇' },
    search: { provider: 'local' },

    footer: {
      message: '@FOOTER_MESSAGE',
      copyright: 'MIT License'
    },
  }
})
