/**
 * @generated from shared-assets/vitepress-template/config.mts.tpl
 * DO NOT EDIT THIS FILE DIRECTLY — edit the template and re-run render-config.py
 *
 * 模板变量（render-config.py 替换）：
 *   observability         e.g. "ai", "java", "clickhouse"
 *   /observability/       e.g. "/ai/", "/clickhouse/"
 *   Observability      e.g. "AI 工程全栈"
 *   现代可观测性深度图谱 - Metrics · Logs · Traces · Profiling · OpenTelemetry · Prometheus · Grafana · SRE 三件套 · 11 大类 · 47 节点       e.g. "系统化学习 AI 工具..."
 *   #14b8a6     e.g. "#8b5cf6"
 *   zh-CN       e.g. "zh-CN"
 *   本站点基于 VitePress 构建 · CC BY-NC-SA 4.0 · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>  e.g. "AI 工程全栈 - 工具 / 大模型 / SDK / Agent"
 *   []   e.g. '[{ icon: "github", link: "https://github.com" }]'
 */
import { defineConfig } from 'vitepress'
import { withMermaid } from 'vitepress-plugin-mermaid'
import { fileURLToPath, URL } from 'node:url'

// P0: VitePress/rollup 默认 fs.allow 限制 cwd 外 import。用 vite alias 解决相对路径。
const SHARED_ASSETS = fileURLToPath(new URL('../../shared-assets', import.meta.url))

export default withMermaid(defineConfig({
  vite: {
    resolve: {
      alias: [
        { find: '@shared', replacement: SHARED_ASSETS },
      ],
    },
  },
  mermaid: { theme: 'default' },
  base: '/observability/',
  title: 'Observability',
  description: '现代可观测性深度图谱 - Metrics · Logs · Traces · Profiling · OpenTelemetry · Prometheus · Grafana · SRE 三件套 · 11 大类 · 47 节点',
  lang: 'zh-CN',
  lastUpdated: true,
  srcDir: 'docs',
  cleanUrls: true,
  ignoreDeadLinks: true,
  head: [
    ['meta', { name: 'viewport', content: 'width=device-width,initial-scale=1,viewport-fit=cover' }],
    ['meta', { name: 'theme-color', content: '#14b8a6' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:locale', content: 'zh_CN' }],
    ['meta', { property: 'og:site_name', content: 'Observability' }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['link', { rel: 'icon', href: '/favicon.svg', type: 'image/svg+xml' }],
    ['link', { rel: 'icon', href: '/favicon.ico', type: 'image/x-icon' }],
    ['link', { rel: 'apple-touch-icon', href: '/apple-touch-icon.png', sizes: '180x180' }],
  ],
  themeConfig: {
    siteTitle: 'Observability',

    // === 统一 nav（C1 规范：顶部 7 项 + 跨站 dropdown）===
    // 1) 门户  2) 首页  3) 知识图谱  4) 思维导图  5) 命令速查  6) 学习路径  7) 更多站点 ▼
    nav: [
      { text: '🏠 门户', link: 'https://java-px.bot.cd/', target: '_blank' },
      { text: '首页', link: '/' },
      { text: '知识图谱', link: '/graph' },
      { text: '思维导图', link: '/mindmap' },
      { text: '命令速查', link: '/cheatsheet' },
      { text: '学习路径', link: '/path' },
      {
        text: '更多站点',
        items: [
                  { text: "ElasticSearch", link: "https://java-px.bot.cd/es/" },
        { text: "MySQL", link: "https://java-px.bot.cd/mysql/" },
        { text: "Redis", link: "https://java-px.bot.cd/redis/" },
        { text: "微服务 / Spring Cloud", link: "https://java-px.bot.cd/cloud/" },
        { text: "Python", link: "https://java-px.bot.cd/python/" },
        { text: "Kafka", link: "https://java-px.bot.cd/kafka/" },
        { text: "Java Web 开发", link: "https://java-px.bot.cd/java/" },
        { text: "在线工具", link: "https://java-px.bot.cd/tools/" },
        { text: "前端 & Node", link: "https://java-px.bot.cd/frontend/" },
        { text: "Linux 服务器", link: "https://java-px.bot.cd/linux/" },
        { text: "云原生 / Docker / K8s", link: "https://java-px.bot.cd/cloud-native/" },
        { text: "AI 工具 / 大模型", link: "https://java-px.bot.cd/ai/" },
        { text: "大数据", link: "https://java-px.bot.cd/bigdata/" },
        { text: "计算机网络", link: "https://java-px.bot.cd/network/" },
        { text: "视频处理", link: "https://java-px.bot.cd/video/" },
        { text: "文件系统与存储", link: "https://java-px.bot.cd/filesystem/" },
        { text: "Java 语言", link: "https://java-px.bot.cd/java-language/" },
        { text: "企业级架构", link: "https://java-px.bot.cd/architecture/" },
        { text: "系统设计", link: "https://java-px.bot.cd/system-design/" },
        { text: "PostgreSQL", link: "https://java-px.bot.cd/postgresql/" },
        { text: "安全", link: "https://java-px.bot.cd/security/" },
        { text: "DevOps", link: "https://java-px.bot.cd/devops/" },
        { text: "Rust", link: "https://java-px.bot.cd/rust/" },
        { text: "Go", link: "https://java-px.bot.cd/go/" },
        { text: "ClickHouse", link: "https://java-px.bot.cd/clickhouse/" },
        { text: "设计模式", link: "https://java-px.bot.cd/design-pattern/" },
        { text: "混沌工程", link: "https://java-px.bot.cd/chaos/" },
        ]
      }
    ],

    // === 各站独立 sidebar（render-config.py 保留原值）===
    sidebar: {
    
              '/': [
                {
                  text: '🏛️ 可观测性基础', collapsed: false, items: [
                    { text: '什么是可观测性', link: '/01-foundations/observability-vs-monitoring' },
                    { text: '四大支柱', link: '/01-foundations/four-pillars' },
                    { text: '信号类型', link: '/01-foundations/signals' },
                    { text: 'SLI / SLO / Error Budget', link: '/01-foundations/sli-slo' }
                  ]
                },
                {
                  text: '🌐 OpenTelemetry', collapsed: false, items: [
                    { text: 'OTel 概览', link: '/02-opentelemetry/overview' },
                    { text: '各语言 SDK', link: '/02-opentelemetry/sdk' },
                    { text: 'OTLP 协议', link: '/02-opentelemetry/otlp' },
                    { text: 'OTel Collector', link: '/02-opentelemetry/collector' },
                    { text: '自动埋点', link: '/02-opentelemetry/auto-instrumentation' }
                  ]
                },
                {
                  text: '📈 Prometheus', collapsed: false, items: [
                    { text: 'Prometheus 架构', link: '/03-prometheus/overview' },
                    { text: '数据模型与 Labels', link: '/03-prometheus/data-model' },
                    { text: 'PromQL 详解', link: '/03-prometheus/promql' },
                    { text: 'Exporter 生态', link: '/03-prometheus/exporter' },
                    { text: '告警规则', link: '/03-prometheus/alert' }
                  ]
                },
                {
                  text: '📊 Grafana', collapsed: false, items: [
                    { text: 'Grafana 安装与数据源', link: '/04-grafana/overview' },
                    { text: 'Dashboard 设计', link: '/04-grafana/dashboard' },
                    { text: '模板变量', link: '/04-grafana/variables' },
                    { text: 'Grafana Alerting', link: '/04-grafana/alerting' },
                    { text: 'Annotation 与联动', link: '/04-grafana/annotation' }
                  ]
                },
                {
                  text: '📜 Loki', collapsed: false, items: [
                    { text: 'Loki 架构', link: '/05-loki/overview' },
                    { text: 'LogQL 查询', link: '/05-loki/logql' },
                    { text: 'Pipeline 配置', link: '/05-loki/pipeline' },
                    { text: '最佳实践', link: '/05-loki/best-practice' }
                  ]
                },
                {
                  text: '🔗 链路追踪', collapsed: false, items: [
                    { text: 'Trace / Span 概念', link: '/06-tracing/concepts' },
                    { text: 'Jaeger', link: '/06-tracing/jaeger' },
                    { text: 'Grafana Tempo', link: '/06-tracing/tempo' },
                    { text: 'Zipkin', link: '/06-tracing/zipkin' },
                    { text: '协议对比', link: '/06-tracing/protocol-compare' }
                  ]
                },
                {
                  text: '🌲 ELK / EFK', collapsed: false, items: [
                    { text: 'ES 作日志存储', link: '/07-elk-efk/elasticsearch-logs' },
                    { text: 'Fluentd 采集', link: '/07-elk-efk/fluentd' },
                    { text: 'Filebeat 轻量采集', link: '/07-elk-efk/filebeat' },
                    { text: 'Kibana 可视化', link: '/07-elk-efk/kibana' }
                  ]
                },
                {
                  text: '🚨 告警与值班', collapsed: false, items: [
                    { text: 'Alertmanager', link: '/08-alerting/alertmanager' },
                    { text: '告警分级 P0/P1/P2', link: '/08-alerting/severity' },
                    { text: '静默 / 抑制 / 分组', link: '/08-alerting/silence' },
                    { text: 'On-call 与故障复盘', link: '/08-alerting/oncall' }
                  ]
                },
                {
                  text: '🧪 应用埋点', collapsed: false, items: [
                    { text: 'RED 方法', link: '/09-app-instrumentation/red-method' },
                    { text: 'USE 方法', link: '/09-app-instrumentation/use-method' },
                    { text: 'JVM 埋点 Micrometer', link: '/09-app-instrumentation/jvm-metrics' },
                    { text: 'K8s 容器监控', link: '/09-app-instrumentation/k8s-metrics' },
                    { text: '业务指标设计', link: '/09-app-instrumentation/business-metrics' }
                  ]
                },
                {
                  text: '🔥 持续剖析', collapsed: false, items: [
                    { text: 'Continuous Profiling', link: '/10-profiling/continuous-profiling' },
                    { text: 'Go pprof', link: '/10-profiling/pprof' },
                    { text: 'Java async-profiler', link: '/10-profiling/async-profiler' },
                    { text: 'Pyroscope 平台', link: '/10-profiling/pyroscope' }
                  ]
                },
                {
                  text: '🌍 实战场景', collapsed: false, items: [
                    { text: 'K8s 全栈监控', link: '/11-scenarios/k8s-monitor' },
                    { text: '数据库监控', link: '/11-scenarios/database-monitor' },
                    { text: '微服务全链路', link: '/11-scenarios/microservice-trace' },
                    { text: '成本优化', link: '/11-scenarios/cost-optimization' }
                  ]
                }
              ]
    },

    socialLinks: [],

    outline: { level: [2, 3], label: '页面大纲' },
    docFooter: { prev: '上一篇', next: '下一篇' },
    search: { provider: 'local' },

    footer: {
      message: '本站点基于 VitePress 构建 · CC BY-NC-SA 4.0 · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>',
      copyright: 'MIT License'
    },
  }
}))
