/**
 * @generated from shared-assets/vitepress-template/config.mts.tpl
 * DO NOT EDIT THIS FILE DIRECTLY — edit the template and re-run render-config.py
 *
 * 模板变量（render-config.py 替换）：
 *   network         e.g. "ai", "java", "clickhouse"
 *   /network/       e.g. "/ai/", "/clickhouse/"
 *   网络全栈      e.g. "AI 工程全栈"
 *   系统化学习计算机网络 - OSI / TCP / UDP / HTTP / DNS / 安全 - 12 大类 · 50+ 节点 · 60+ 内容页       e.g. "系统化学习 AI 工具..."
 *   #0ea5e9     e.g. "#8b5cf6"
 *   zh-CN       e.g. "zh-CN"
 *   计算机网络全栈 - TCP/IP 协议栈 / 网络安全 / 云网络 · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>  e.g. "AI 工程全栈 - 工具 / 大模型 / SDK / Agent"
 *   [{ icon: 'github', link: 'https://github.com' }]   e.g. '[{ icon: "github", link: "https://github.com" }]'
 */
import { defineConfig } from 'vitepress'
import { fileURLToPath, URL } from 'node:url'

// P0: VitePress/rollup 默认 fs.allow 限制 cwd 外 import。用 vite alias 解决相对路径。
const SHARED_ASSETS = fileURLToPath(new URL('../../shared-assets', import.meta.url))

export default defineConfig({
  vite: {
    resolve: {
      alias: [
        { find: '@shared', replacement: SHARED_ASSETS },
      ],
    },
  },
  base: '/network/',
  title: '网络全栈',
  description: '系统化学习计算机网络 - OSI / TCP / UDP / HTTP / DNS / 安全 - 12 大类 · 50+ 节点 · 60+ 内容页',
  lang: 'zh-CN',
  lastUpdated: true,
  srcDir: 'docs',
  cleanUrls: true,
  ignoreDeadLinks: true,
  head: [
    ['meta', { name: 'viewport', content: 'width=device-width,initial-scale=1,viewport-fit=cover' }],
    ['meta', { name: 'theme-color', content: '#0ea5e9' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:locale', content: 'zh_CN' }],
    ['meta', { property: 'og:site_name', content: '网络全栈' }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['link', { rel: 'icon', href: '/favicon.svg', type: 'image/svg+xml' }],
    ['link', { rel: 'icon', href: '/favicon.ico', type: 'image/x-icon' }],
    ['link', { rel: 'apple-touch-icon', href: '/apple-touch-icon.png', sizes: '180x180' }],
  ],
  themeConfig: {
    siteTitle: '网络全栈',

    // === 统一 nav（C1 规范：顶部 7 项 + 跨站 dropdown）===
    // 1) 门户  2) 首页  3) 知识图谱  4) 思维导图  5) 命令速查  6) 学习路径  7) 更多站点 ▼
    nav: [
      { text: '🏠 门户', link: 'https://java-px.bot.cd/', target: '_blank' },
      { text: '首页', link: '/' },
      { text: '知识图谱', link: '/graph' },
      { text: '思维导图', link: '/mindmap' },
      { text: '命令速查', link: '/cheatsheet' },
      { text: '学习路径', link: '/path' },
      {
        text: '更多站点',
        items: [
                  { text: "ElasticSearch", link: "https://java-px.bot.cd/es/" },
        { text: "MySQL", link: "https://java-px.bot.cd/mysql/" },
        { text: "Redis", link: "https://java-px.bot.cd/redis/" },
        { text: "微服务 / Spring Cloud", link: "https://java-px.bot.cd/cloud/" },
        { text: "Python", link: "https://java-px.bot.cd/python/" },
        { text: "Kafka", link: "https://java-px.bot.cd/kafka/" },
        { text: "Java Web 开发", link: "https://java-px.bot.cd/java/" },
        { text: "在线工具", link: "https://java-px.bot.cd/tools/" },
        { text: "前端 & Node", link: "https://java-px.bot.cd/frontend/" },
        { text: "Linux 服务器", link: "https://java-px.bot.cd/linux/" },
        { text: "云原生 / Docker / K8s", link: "https://java-px.bot.cd/cloud-native/" },
        { text: "AI 工具 / 大模型", link: "https://java-px.bot.cd/ai/" },
        { text: "大数据", link: "https://java-px.bot.cd/bigdata/" },
        { text: "视频处理", link: "https://java-px.bot.cd/video/" },
        { text: "文件系统与存储", link: "https://java-px.bot.cd/filesystem/" },
        { text: "Java 语言", link: "https://java-px.bot.cd/java-language/" },
        { text: "企业级架构", link: "https://java-px.bot.cd/architecture/" },
        { text: "系统设计", link: "https://java-px.bot.cd/system-design/" },
        { text: "PostgreSQL", link: "https://java-px.bot.cd/postgresql/" },
        { text: "可观测性", link: "https://java-px.bot.cd/observability/" },
        { text: "安全", link: "https://java-px.bot.cd/security/" },
        { text: "DevOps", link: "https://java-px.bot.cd/devops/" },
        { text: "Rust", link: "https://java-px.bot.cd/rust/" },
        { text: "Go", link: "https://java-px.bot.cd/go/" },
        { text: "ClickHouse", link: "https://java-px.bot.cd/clickhouse/" },
        { text: "设计模式", link: "https://java-px.bot.cd/design-pattern/" },
        { text: "混沌工程", link: "https://java-px.bot.cd/chaos/" },
        { text: "物联网", link: "https://java-px.bot.cd/iot/" },
        { text: "安卓", link: "https://java-px.bot.cd/android/" },
        { text: "游戏开发", link: "https://java-px.bot.cd/game/" },
        ]
      }
    ],

    // === 各站独立 sidebar（render-config.py 保留原值）===
    sidebar: {
    
        
            
                              '/': [
                                {
                                  text: '🎯 开始',
                                  items: [
                                    { text: '📖 学习路径', link: '/path' },
                                    { text: '🧠 知识图谱', link: '/graph' },
                                    { text: '🧭 思维导图', link: '/mindmap' },
                                    { text: '⚡ 速记卡', link: '/cheatsheet' }
                                  ]
                                },
                                {
                                  text: '🌐 网络基础',
                                  items: [
                                    { text: 'OSI 七层模型', link: '/01-basics/osi' },
                                    { text: 'TCP/IP 四层模型', link: '/01-basics/tcp-ip' },
                                    { text: '数据封装与解封装', link: '/01-basics/encapsulation' },
                                    { text: '网络性能指标', link: '/01-basics/metrics' }
                                  ]
                                },
                                {
                                  text: '🔌 物理层',
                                  items: [
                                    { text: '信号与编码', link: '/02-physical/signal' },
                                    { text: '传输介质', link: '/02-physical/media' },
                                    { text: '复用技术', link: '/02-physical/multiplexing' }
                                  ]
                                },
                                {
                                  text: '🔗 数据链路层',
                                  items: [
                                    { text: 'MAC 地址', link: '/03-data-link/mac' },
                                    { text: '以太网 / 交换机', link: '/03-data-link/ethernet' },
                                    { text: 'VLAN', link: '/03-data-link/vlan' },
                                    { text: 'STP / RSTP', link: '/03-data-link/stp' }
                                  ]
                                },
                                {
                                  text: '🌍 网络层',
                                  items: [
                                    { text: 'IP 地址', link: '/04-network/ip-address' },
                                    { text: '子网划分 / VLSM', link: '/04-network/subnet' },
                                    { text: 'IPv6 协议', link: '/04-network/ipv6' },
                                    { text: 'ARP 协议', link: '/04-network/arp' },
                                    { text: 'ICMP / ping', link: '/04-network/icmp' },
                                    { text: 'IP 路由', link: '/04-network/routing' },
                                    { text: 'OSPF / BGP', link: '/04-network/bgp-ospf' },
                                    { text: 'NAT', link: '/04-network/nat' }
                                  ]
                                },
                                {
                                  text: '🚚 传输层',
                                  items: [
                                    { text: 'UDP 协议', link: '/05-transport/udp' },
                                    { text: 'TCP 三次握手', link: '/05-transport/tcp-handshake' },
                                    { text: 'TCP 四次挥手', link: '/05-transport/tcp-wave' },
                                    { text: 'TCP 可靠传输', link: '/05-transport/tcp-reliable' },
                                    { text: 'TCP 流量控制', link: '/05-transport/tcp-flow-control' },
                                    { text: 'TCP 拥塞控制', link: '/05-transport/tcp-congestion' },
                                    { text: 'Socket 编程', link: '/05-transport/socket' }
                                  ]
                                },
                                {
                                  text: '📱 应用层',
                                  items: [
                                    { text: 'HTTP 协议', link: '/06-application/http' },
                                    { text: 'HTTPS / TLS', link: '/06-application/https' },
                                    { text: 'HTTP/2 / HTTP/3', link: '/06-application/http2-3' },
                                    { text: 'DNS 域名解析', link: '/06-application/dns' },
                                    { text: 'CDN 加速', link: '/06-application/cdn' },
                                    { text: 'WebSocket', link: '/06-application/websocket' },
                                    { text: 'RESTful API', link: '/06-application/restful' },
                                    { text: 'RPC 协议', link: '/06-application/rpc' }
                                  ]
                                },
                                {
                                  text: '🔒 网络安全',
                                  items: [
                                    { text: '对称 / 非对称加密', link: '/07-security/encryption' },
                                    { text: '数字签名 / PKI', link: '/07-security/signature-pki' },
                                    { text: 'PKI / TLS 实战', link: '/07-security/pki-tls' },
                                    { text: '常见网络攻击', link: '/07-security/network-attack' },
                                    { text: '防火墙 / VPN', link: '/07-security/firewall-vpn' },
                                    { text: '无线安全', link: '/07-security/wireless-security' },
                                    { text: 'SIEM / WAF', link: '/07-security/siem-waf' }
                                  ]
                                },
                                {
                                  text: '📡 无线网络',
                                  items: [
                                    { text: 'WiFi 原理', link: '/08-wireless/wifi' },
                                    { text: '5G 与移动网络', link: '/08-wireless/5g' },
                                    { text: '蓝牙与短距', link: '/08-wireless/bluetooth' },
                                    { text: '物联网通信', link: '/08-wireless/iot' }
                                  ]
                                },
                                {
                                  text: '☁️ 云网络',
                                  items: [
                                    { text: 'VPC 虚拟私有云', link: '/09-cloud-network/vpc' },
                                    { text: '负载均衡 SLB', link: '/09-cloud-network/slb' },
                                    { text: 'SDN / Service Mesh', link: '/09-cloud-network/sdn-service-mesh' },
                                    { text: '云上 DNS / CDN', link: '/09-cloud-network/dns-cdn' }
                                  ]
                                },
                                {
                                  text: '🛠️ 抓包与排查',
                                  items: [
                                    { text: 'Wireshark 抓包', link: '/10-tools/wireshark' },
                                    { text: 'tcpdump / curl', link: '/10-tools/tcpdump-curl' },
                                    { text: '网络性能测试', link: '/10-tools/performance-test' },
                                    { text: '故障排查方法', link: '/10-tools/troubleshooting' },
                                    { text: '网络监控', link: '/10-tools/monitoring' }
                                  ]
                                },
                                {
                                  text: '🏢 企业案例',
                                  items: [
                                    { text: 'CDN 全站加速', link: '/11-cases/cdn-case' },
                                    { text: '微服务网络', link: '/11-cases/microservice-network' },
                                    { text: 'HTTPS 性能优化', link: '/11-cases/https-https' },
                                    { text: '跨地域组网', link: '/11-cases/cross-region' }
                                  ]
                                },
                                {
                                  text: '🎯 面试 / 实战',
                                  items: [
                                    { text: '高频面试题', link: '/12-interview-practice/questions' },
                                    { text: '案例题', link: '/12-interview-practice/cases' },
                                    { text: '协议对比', link: '/12-interview-practice/comparison' }
                                  ]
                                }
                              ]
    },

    socialLinks: [{ icon: 'github', link: 'https://github.com' }],

    outline: { level: [2, 3], label: '页面大纲' },
    docFooter: { prev: '上一篇', next: '下一篇' },
    search: { provider: 'local' },

    footer: {
      message: '计算机网络全栈 - TCP/IP 协议栈 / 网络安全 / 云网络 · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>',
      copyright: 'MIT License'
    },
  }
})
