/**
 * @generated from shared-assets/vitepress-template/config.mts.tpl
 * DO NOT EDIT THIS FILE DIRECTLY — edit the template and re-run render-config.py
 *
 * 模板变量（render-config.py 替换）：
 *   game         e.g. "ai", "java", "clickhouse"
 *   /game/       e.g. "/ai/", "/clickhouse/"
 *   Game      e.g. "AI 工程全栈"
 *   游戏开发全栈知识图谱 - Unity / Unreal / Godot / 渲染 / 物理 / AI / 网络 · 8 大类 · 110 节点       e.g. "系统化学习 AI 工具..."
 *   #9146FF     e.g. "#8b5cf6"
 *   zh-CN       e.g. "zh-CN"
 *   游戏开发全栈知识图谱 - Unity / Unreal / Godot / 渲染 / 物理 / AI · 📚 <a href="https://java-px.bot.cd/game/" target="_blank">game 站主页</a> · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>  e.g. "AI 工程全栈 - 工具 / 大模型 / SDK / Agent"
 *   []   e.g. '[{ icon: "github", link: "https://github.com" }]'
 */
import { defineConfig } from 'vitepress'
import { withMermaid } from 'vitepress-plugin-mermaid'
import { fileURLToPath, URL } from 'node:url'

// P0: VitePress/rollup 默认 fs.allow 限制 cwd 外 import。用 vite alias 解决相对路径。
const SHARED_ASSETS = fileURLToPath(new URL('../../shared-assets', import.meta.url))

// C11: Mermaid 跨站共享配置（inline 而非 import，避免 vite alias 在 Node 加载 config.mts 阶段不生效的问题）
// 同步源：shared-assets/mermaid-config/base.ts（修改时请同步更新此处）
// 见 §8.46
const mermaidBase = {
  securityLevel: 'loose',
  startOnLoad: false,
  theme: 'base',
  fontFamily: '"Inter", "PingFang SC", "Microsoft YaHei", system-ui, -apple-system, sans-serif',
} as const

function lightenHex(hex: string, ratio: number): string {
  const m = hex.replace('#', '').match(/^([0-9a-f]{6})$/i)
  if (!m) return hex
  const r = parseInt(m[1].slice(0, 2), 16)
  const g = parseInt(m[1].slice(2, 4), 16)
  const b = parseInt(m[1].slice(4, 6), 16)
  const mix = (c: number) => Math.round(c + (255 - c) * ratio)
  return '#' + [mix(r), mix(g), mix(b)].map(c => c.toString(16).padStart(2, '0')).join('')
}

function mermaidTheme(brand: string) {
  const soft = lightenHex(brand, 0.85)
  const ink = '#1f2937'
  const line = '#94a3b8'
  return {
    primaryColor: brand,
    primaryTextColor: ink,
    primaryBorderColor: brand,
    lineColor: line,
    secondaryColor: soft,
    tertiaryColor: '#fafafa',
    fontFamily: mermaidBase.fontFamily,
    fontSize: '14px',
  }
}

export default withMermaid( defineConfig({
  vite: {
    resolve: {
      alias: [
        { find: '@shared', replacement: SHARED_ASSETS },
      ],
    },
    // §8.72：shared-assets/svg/ 共享 SVG 资产（CAP / Saga / 一致性 hash 等）
    publicDir: fileURLToPath(new URL('../../shared-assets/svg', import.meta.url)),
  },
    mermaid: {
    ...mermaidBase,
    themeVariables: mermaidTheme('#9146FF'),
  },
    base: '/game/',
  title: 'Game',
  description: '游戏开发全栈知识图谱 - Unity / Unreal / Godot / 渲染 / 物理 / AI / 网络 · 8 大类 · 110 节点',
  lang: 'zh-CN',
  lastUpdated: true,
  srcDir: 'docs',
  cleanUrls: true,
  ignoreDeadLinks: true,
  head: [
    ['meta', { name: 'viewport', content: 'width=device-width,initial-scale=1,viewport-fit=cover' }],
    ['meta', { name: 'theme-color', content: '#9146FF' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:locale', content: 'zh_CN' }],
    ['meta', { property: 'og:site_name', content: 'Game' }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['link', { rel: 'icon', href: '/favicon.svg', type: 'image/svg+xml' }],
    ['link', { rel: 'icon', href: '/favicon.ico', type: 'image/x-icon' }],
    ['link', { rel: 'apple-touch-icon', href: '/apple-touch-icon.png', sizes: '180x180' }],
  ],
  themeConfig: {
    siteTitle: 'Game',

    // === 统一 nav（C1 规范：顶部 7 项 + 跨站 dropdown）===
    // 1) 门户  2) 首页  3) 知识图谱  4) 思维导图  5) 命令速查  6) 学习路径  7) 更多站点 ▼
    nav: [
      { text: '🏠 门户', link: 'https://java-px.bot.cd/', target: '_blank' },
      { text: '首页', link: '/' },
      { text: '知识图谱', link: '/graph' },
      { text: '思维导图', link: '/mindmap' },
      { text: '命令速查', link: '/cheatsheet' },
      { text: '学习路径', link: '/path' },
      {
        text: '更多站点',
        items: [
                  { text: "ElasticSearch", link: "https://java-px.bot.cd/es/" },
        { text: "MySQL", link: "https://java-px.bot.cd/mysql/" },
        { text: "Redis", link: "https://java-px.bot.cd/redis/" },
        { text: "微服务 / Spring Cloud", link: "https://java-px.bot.cd/cloud/" },
        { text: "Python", link: "https://java-px.bot.cd/python/" },
        { text: "Kafka", link: "https://java-px.bot.cd/kafka/" },
        { text: "Java Web 开发", link: "https://java-px.bot.cd/java/" },
        { text: "在线工具", link: "https://java-px.bot.cd/tools/" },
        { text: "前端 & Node", link: "https://java-px.bot.cd/frontend/" },
        { text: "Linux 服务器", link: "https://java-px.bot.cd/linux/" },
        { text: "云原生 / Docker / K8s", link: "https://java-px.bot.cd/cloud-native/" },
        { text: "AI 工具 / 大模型", link: "https://java-px.bot.cd/ai/" },
        { text: "大数据", link: "https://java-px.bot.cd/bigdata/" },
        { text: "计算机网络", link: "https://java-px.bot.cd/network/" },
        { text: "视频处理", link: "https://java-px.bot.cd/video/" },
        { text: "文件系统与存储", link: "https://java-px.bot.cd/filesystem/" },
        { text: "Java 语言", link: "https://java-px.bot.cd/java-language/" },
        { text: "企业级架构", link: "https://java-px.bot.cd/architecture/" },
        { text: "系统设计", link: "https://java-px.bot.cd/system-design/" },
        { text: "PostgreSQL", link: "https://java-px.bot.cd/postgresql/" },
        { text: "可观测性", link: "https://java-px.bot.cd/observability/" },
        { text: "安全", link: "https://java-px.bot.cd/security/" },
        { text: "DevOps", link: "https://java-px.bot.cd/devops/" },
        { text: "Rust", link: "https://java-px.bot.cd/rust/" },
        { text: "Go", link: "https://java-px.bot.cd/go/" },
        { text: "ClickHouse", link: "https://java-px.bot.cd/clickhouse/" },
        { text: "设计模式", link: "https://java-px.bot.cd/design-pattern/" },
        { text: "混沌工程", link: "https://java-px.bot.cd/chaos/" },
        { text: "物联网", link: "https://java-px.bot.cd/iot/" },
        { text: "安卓", link: "https://java-px.bot.cd/android/" },
        ]
      }
    ],

    // === 各站独立 sidebar（render-config.py 保留原值）===
    sidebar: {
    
        
            
                              '/': [
                                {
                                  text: '🎮 游戏开发总览',
                                  collapsed: false,
                                  items: [
                                    { text: '首页', link: '/' },
                                    { text: '知识图谱位置', link: '/README' },
                                  ]
                                },
                                {
                                  text: '🗺️ 结构图',
                                  collapsed: false,
                                  items: [
                                    { text: '思维导图', link: '/mindmap' },
                                  ]
                                },
                                {
                                  text: '🎮 引擎层',
                                  collapsed: false,
                                  items: [
                                    { text: '章节目录', link: '/01-engine/' },
                                    { text: '商业引擎选型', link: '/01-engine/commercial' },
                                    { text: '自研引擎架构', link: '/01-engine/custom' },
                                    { text: '选型决策', link: '/01-engine/decision' },
                                  ]
                                },
                                {
                                  text: '🎨 渲染',
                                  collapsed: false,
                                  items: [
                                    { text: '章节目录', link: '/02-render/' },
                                    { text: '渲染管线', link: '/02-render/pipeline' },
                                    { text: '光照与阴影', link: '/02-render/lighting' },
                                    { text: '着色器', link: '/02-render/shader' },
                                    { text: '后处理', link: '/02-render/postprocess' },
                                  ]
                                },
                                {
                                  text: '⚙️ 物理',
                                  collapsed: false,
                                  items: [
                                    { text: '章节目录', link: '/03-physics/' },
                                    { text: '碰撞检测', link: '/03-physics/collision' },
                                    { text: '刚体动力学', link: '/03-physics/rigidbody' },
                                    { text: '柔体模拟', link: '/03-physics/softbody' },
                                  ]
                                },
                                {
                                  text: '🤖 AI',
                                  collapsed: false,
                                  items: [
                                    { text: '章节目录', link: '/04-ai/' },
                                    { text: '寻路', link: '/04-ai/pathfinding' },
                                    { text: '决策系统', link: '/04-ai/decision' },
                                    { text: '机器学习 AI', link: '/04-ai/ml' },
                                  ]
                                },
                                {
                                  text: '🌐 网络',
                                  collapsed: false,
                                  items: [
                                    { text: '章节目录', link: '/05-network/' },
                                    { text: '同步模型', link: '/05-network/sync' },
                                    { text: '一致性', link: '/05-network/consistency' },
                                    { text: '反外挂', link: '/05-network/anticheat' },
                                    { text: '联机架构', link: '/05-network/arch' },
                                  ]
                                },
                                {
                                  text: '🔊 音频',
                                  collapsed: false,
                                  items: [
                                    { text: '章节目录', link: '/06-audio/' },
                                    { text: '空间音频', link: '/06-audio/spatial' },
                                    { text: '动态混音', link: '/06-audio/mix' },
                                    { text: '音频引擎', link: '/06-audio/engine' },
                                  ]
                                },
                                {
                                  text: '🛠️ 工具链',
                                  collapsed: false,
                                  items: [
                                    { text: '章节目录', link: '/07-toolchain/' },
                                    { text: '资产管线', link: '/07-toolchain/assets' },
                                    { text: '版本控制', link: '/07-toolchain/vcs' },
                                    { text: '构建发布', link: '/07-toolchain/build' },
                                  ]
                                },
                                {
                                  text: '🚀 性能与上线',
                                  collapsed: false,
                                  items: [
                                    { text: '章节目录', link: '/08-ship/' },
                                    { text: '性能优化', link: '/08-ship/perf' },
                                    { text: '上线运营', link: '/08-ship/launch' },
                                  ]
                                },
                                {
                                  text: '🚶 学习',
                                  collapsed: false,
                                  items: [
                                    { text: '学习路径', link: '/path' },
                                    { text: '常见问题', link: '/questions' },
                                    { text: '速查表', link: '/cheatsheet' },
                                  ]
                                }
                              ]
    },

    socialLinks: [],

    outline: { level: [2, 3], label: '页面大纲' },
    docFooter: { prev: '上一篇', next: '下一篇' },
    search: { provider: 'local' },

    footer: {
      message: '游戏开发全栈知识图谱 - Unity / Unreal / Godot / 渲染 / 物理 / AI · 📚 <a href="https://java-px.bot.cd/game/" target="_blank">game 站主页</a> · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>',
      copyright: 'MIT License'
    },
  }
}))
