/**
 * @generated from shared-assets/vitepress-template/config.mts.tpl
 * DO NOT EDIT THIS FILE DIRECTLY — edit the template and re-run render-config.py
 *
 * 模板变量（render-config.py 替换）：
 *   iot         e.g. "ai", "java", "clickhouse"
 *   /clickhouse/       e.g. "/ai/", "/clickhouse/"
 *   ClickHouse      e.g. "AI 工程全栈"
 *   OLAP 列式数据库深度图谱 - MergeTree / 主键索引 / 数据分区 / 向量化执行 / 实时数仓 · Kafka 引擎 / Grafana / Prometheus · vs Doris / StarRocks / TiDB / Snowflake · 6 大类 · 35 节点       e.g. "系统化学习 AI 工具..."
 *   #FFCC01     e.g. "#8b5cf6"
 *   zh-CN       e.g. "zh-CN"
 *   ClickHouse 是 Yandex 开源的高性能列式 OLAP 数据库 · <a href="https://clickhouse.com/" target="_blank">clickhouse.com</a> · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>  e.g. "AI 工程全栈 - 工具 / 大模型 / SDK / Agent"
 *   []   e.g. '[{ icon: "github", link: "https://github.com" }]'
 */
import { defineConfig } from 'vitepress'
import { withMermaid } from 'vitepress-plugin-mermaid'
import { fileURLToPath, URL } from 'node:url'

// P0: VitePress/rollup 默认 fs.allow 限制 cwd 外 import。用 vite alias 解决相对路径。
const SHARED_ASSETS = fileURLToPath(new URL('../../shared-assets', import.meta.url))

// C11: Mermaid 跨站共享配置（inline 而非 import，避免 vite alias 在 Node 加载 config.mts 阶段不生效的问题）
// 同步源：shared-assets/mermaid-config/base.ts（修改时请同步更新此处）
// 见 §8.46
const mermaidBase = {
  securityLevel: 'loose',
  startOnLoad: false,
  theme: 'base',
  fontFamily: '"Inter", "PingFang SC", "Microsoft YaHei", system-ui, -apple-system, sans-serif',
} as const

function lightenHex(hex: string, ratio: number): string {
  const m = hex.replace('#', '').match(/^([0-9a-f]{6})$/i)
  if (!m) return hex
  const r = parseInt(m[1].slice(0, 2), 16)
  const g = parseInt(m[1].slice(2, 4), 16)
  const b = parseInt(m[1].slice(4, 6), 16)
  const mix = (c: number) => Math.round(c + (255 - c) * ratio)
  return '#' + [mix(r), mix(g), mix(b)].map(c => c.toString(16).padStart(2, '0')).join('')
}

function mermaidTheme(brand: string) {
  const soft = lightenHex(brand, 0.85)
  const ink = '#1f2937'
  const line = '#94a3b8'
  return {
    primaryColor: brand,
    primaryTextColor: ink,
    primaryBorderColor: brand,
    lineColor: line,
    secondaryColor: soft,
    tertiaryColor: '#fafafa',
    fontFamily: mermaidBase.fontFamily,
    fontSize: '14px',
  }
}

export default withMermaid(defineConfig({
  vite: {
    resolve: {
      alias: [
        { find: '@shared', replacement: SHARED_ASSETS },
      ],
    },
  },
  mermaid: {
    ...mermaidBase,
    themeVariables: mermaidTheme('#9146FF'),
  },
  base: '/game/',
  title: 'Game',
  description: '游戏开发全栈知识图谱 - Unity / Unreal / Godot / 渲染 / 物理 / AI / 网络 · 8 大类 · 110 节点',
  lang: 'zh-CN',
  lastUpdated: true,
  srcDir: 'docs',
  cleanUrls: true,
  ignoreDeadLinks: true,
  head: [
    ['meta', { name: 'viewport', content: 'width=device-width,initial-scale=1,viewport-fit=cover' }],
    ['meta', { name: 'theme-color', content: '#9146FF' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:locale', content: 'zh_CN' }],
    ['meta', { property: 'og:site_name', content: 'Game' }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['link', { rel: 'icon', href: '/favicon.svg', type: 'image/svg+xml' }],
    ['link', { rel: 'icon', href: '/favicon.ico', type: 'image/x-icon' }],
    ['link', { rel: 'apple-touch-icon', href: '/apple-touch-icon.png', sizes: '180x180' }],
  ],
  themeConfig: {
    siteTitle: 'Game',

    // === 统一 nav（C1 规范：顶部 7 项 + 跨站 dropdown）===
    // 1) 门户  2) 首页  3) 知识图谱  4) 思维导图  5) 命令速查  6) 学习路径  7) 更多站点 ▼
    nav: [
      { text: '🏠 门户', link: 'https://java-px.bot.cd/', target: '_blank' },
      { text: '首页', link: '/' },
      { text: '知识图谱', link: '/README' },
      { text: '思维导图', link: '/mindmap' },
      { text: '命令速查', link: '/cheatsheet' },
      { text: '学习路径', link: '/path' },
      {
        text: '更多站点',
        items: [
                  { text: "ElasticSearch", link: "https://java-px.bot.cd/es/" },
        { text: "MySQL", link: "https://java-px.bot.cd/mysql/" },
        { text: "Redis", link: "https://java-px.bot.cd/redis/" },
        { text: "微服务 / Spring Cloud", link: "https://java-px.bot.cd/cloud/" },
        { text: "Python", link: "https://java-px.bot.cd/python/" },
        { text: "Kafka", link: "https://java-px.bot.cd/kafka/" },
        { text: "Java Web 开发", link: "https://java-px.bot.cd/java/" },
        { text: "在线工具", link: "https://java-px.bot.cd/tools/" },
        { text: "前端 & Node", link: "https://java-px.bot.cd/frontend/" },
        { text: "Linux 服务器", link: "https://java-px.bot.cd/linux/" },
        { text: "云原生 / Docker / K8s", link: "https://java-px.bot.cd/cloud-native/" },
        { text: "AI 工具 / 大模型", link: "https://java-px.bot.cd/ai/" },
        { text: "大数据", link: "https://java-px.bot.cd/bigdata/" },
        { text: "计算机网络", link: "https://java-px.bot.cd/network/" },
        { text: "视频处理", link: "https://java-px.bot.cd/video/" },
        { text: "文件系统与存储", link: "https://java-px.bot.cd/filesystem/" },
        { text: "Java 语言", link: "https://java-px.bot.cd/java-language/" },
        { text: "企业级架构", link: "https://java-px.bot.cd/architecture/" },
        { text: "系统设计", link: "https://java-px.bot.cd/system-design/" },
        { text: "PostgreSQL", link: "https://java-px.bot.cd/postgresql/" },
        { text: "可观测性", link: "https://java-px.bot.cd/observability/" },
        { text: "安全", link: "https://java-px.bot.cd/security/" },
        { text: "DevOps", link: "https://java-px.bot.cd/devops/" },
        { text: "Rust", link: "https://java-px.bot.cd/rust/" },
        { text: "Go", link: "https://java-px.bot.cd/go/" },
        { text: "Game", link: "https://java-px.bot.cd/game/" },
        { text: "设计模式", link: "https://java-px.bot.cd/design-pattern/" },
        { text: "混沌工程", link: "https://java-px.bot.cd/chaos/" },
        ]
      }
    ],

    // === 各站独立 sidebar（render-config.py 保留原值）===
        sidebar: {
      '/': [
        {
          text: '🎮 游戏开发总览',
          collapsed: false,
          items: [
            { text: '首页', link: '/' },
            { text: '知识图谱位置', link: '/README' },
          ]
        },
        {
          text: '🗺️ 结构图',
          collapsed: false,
          items: [
            { text: '思维导图', link: '/mindmap' },
          ]
        },
        {
          text: '🚶 学习',
          collapsed: false,
          items: [
            { text: '学习路径', link: '/path' },
            { text: '常见问题', link: '/questions' },
            { text: '速查表', link: '/cheatsheet' },
          ]
        }
      ]
    },

    socialLinks: [],

    outline: { level: [2, 3], label: '页面大纲' },
    docFooter: { prev: '上一篇', next: '下一篇' },
    search: { provider: 'local' },

    footer: {
      message: '游戏开发全栈知识图谱 - Unity / Unreal / Godot / 渲染 / 物理 / AI · 📚 <a href="https://java-px.bot.cd/game/" target="_blank">game 站主页</a> · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>',
      copyright: 'MIT License'
    },
  }
}))
