/**
 * @generated from shared-assets/vitepress-template/config.mts.tpl
 * DO NOT EDIT THIS FILE DIRECTLY — edit the template and re-run render-config.py
 *
 * 模板变量（render-config.py 替换）：
 *   architecture         e.g. "ai", "java", "clickhouse"
 *   /architecture/       e.g. "/ai/", "/clickhouse/"
 *   企业级架构      e.g. "AI 工程全栈"
 *   系统化学习高可用 / 高并发 / 微服务 / DDD - 14 大类 · 50+ 节点 · 50+ 内容页       e.g. "系统化学习 AI 工具..."
 *   #7c3aed     e.g. "#8b5cf6"
 *   zh-CN       e.g. "zh-CN"
 *   企业级架构 - 高可用 / 高并发 / 微服务 / DDD · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>  e.g. "AI 工程全栈 - 工具 / 大模型 / SDK / Agent"
 *   [{icon:'github',link:'https://github.com'}]   e.g. '[{ icon: "github", link: "https://github.com" }]'
 */
import { defineConfig } from 'vitepress'
import { withMermaid } from 'vitepress-plugin-mermaid'
import { fileURLToPath, URL } from 'node:url'

// P0: VitePress/rollup 默认 fs.allow 限制 cwd 外 import。用 vite alias 解决相对路径。
const SHARED_ASSETS = fileURLToPath(new URL('../../shared-assets', import.meta.url))

// P0: shared-assets/ 下的 .vue 组件 import vue 时需要显式 alias 指向本站点 node_modules。
// 否则 rollup 在 SHARED_ASSETS 目录找不到 vue，会报 "Rollup failed to resolve import 'vue'"。
// §8.81 QrShare 落地后暴露此问题。
const VUE = fileURLToPath(new URL('../node_modules/vue', import.meta.url))

// C11: Mermaid 跨站共享配置（inline 而非 import，避免 vite alias 在 Node 加载 config.mts 阶段不生效的问题）
// 同步源：shared-assets/mermaid-config/base.ts（修改时请同步更新此处）
// 见 §8.46
const mermaidBase = {
  securityLevel: 'loose',
  startOnLoad: false,
  theme: 'base',
  fontFamily: '"Inter", "PingFang SC", "Microsoft YaHei", system-ui, -apple-system, sans-serif',
} as const

function lightenHex(hex: string, ratio: number): string {
  const m = hex.replace('#', '').match(/^([0-9a-f]{6})$/i)
  if (!m) return hex
  const r = parseInt(m[1].slice(0, 2), 16)
  const g = parseInt(m[1].slice(2, 4), 16)
  const b = parseInt(m[1].slice(4, 6), 16)
  const mix = (c: number) => Math.round(c + (255 - c) * ratio)
  return '#' + [mix(r), mix(g), mix(b)].map(c => c.toString(16).padStart(2, '0')).join('')
}

function mermaidTheme(brand: string) {
  const soft = lightenHex(brand, 0.85)
  const ink = '#1f2937'
  const line = '#94a3b8'
  return {
    primaryColor: brand,
    primaryTextColor: ink,
    primaryBorderColor: brand,
    lineColor: line,
    secondaryColor: soft,
    tertiaryColor: '#fafafa',
    fontFamily: mermaidBase.fontFamily,
    fontSize: '14px',
  }
}

export default withMermaid( defineConfig({
  vite: {
    resolve: {
      alias: [
        { find: '@shared', replacement: SHARED_ASSETS },
        { find: /^vue$/, replacement: VUE },
      ],
    },
    // §8.72：shared-assets/svg/ 共享 SVG 资产（CAP / Saga / 一致性 hash 等）
    // 只把 svg/ 子目录作为 public（避免泄漏 mermaid-config / glossary / template 等）
    publicDir: fileURLToPath(new URL('../../shared-assets/svg', import.meta.url)),
  },
    mermaid: {
    ...mermaidBase,
    themeVariables: mermaidTheme('#7c3aed'),
  },
    base: '/architecture/',
  title: '企业级架构',
  description: '系统化学习高可用 / 高并发 / 微服务 / DDD - 14 大类 · 50+ 节点 · 50+ 内容页',
  lang: 'zh-CN',
  lastUpdated: true,
  srcDir: 'docs',
  cleanUrls: true,
  ignoreDeadLinks: true,
  head: [
    ['meta', { name: 'viewport', content: 'width=device-width,initial-scale=1,viewport-fit=cover' }],
    ['meta', { name: 'theme-color', content: '#7c3aed' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:locale', content: 'zh_CN' }],
    ['meta', { property: 'og:site_name', content: '企业级架构' }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['link', { rel: 'icon', href: '/favicon.svg', type: 'image/svg+xml' }],
    ['link', { rel: 'icon', href: '/favicon.ico', type: 'image/x-icon' }],
    ['link', { rel: 'apple-touch-icon', href: '/apple-touch-icon.png', sizes: '180x180' }],
  ],
  themeConfig: {
    siteTitle: '企业级架构',

    // === 统一 nav（C1 规范：顶部 7 项 + 跨站 dropdown）===
    // 1) 门户  2) 首页  3) 知识图谱  4) 思维导图  5) 命令速查  6) 学习路径  7) 更多站点 ▼
    nav: [
      { text: '🏠 门户', link: 'https://java-px.bot.cd/', target: '_blank' },
      { text: '首页', link: '/' },
      { text: '知识图谱', link: '/graph' },
      { text: '思维导图', link: '/mindmap' },
      { text: '命令速查', link: '/cheatsheet' },
      { text: '学习路径', link: '/path' },
      {
        text: '更多站点',
        items: [
                  { text: "ElasticSearch", link: "https://java-px.bot.cd/es/" },
        { text: "MySQL", link: "https://java-px.bot.cd/mysql/" },
        { text: "Redis", link: "https://java-px.bot.cd/redis/" },
        { text: "微服务 / Spring Cloud", link: "https://java-px.bot.cd/cloud/" },
        { text: "Python", link: "https://java-px.bot.cd/python/" },
        { text: "Kafka", link: "https://java-px.bot.cd/kafka/" },
        { text: "Java Web 开发", link: "https://java-px.bot.cd/java/" },
        { text: "在线工具", link: "https://java-px.bot.cd/tools/" },
        { text: "前端 & Node", link: "https://java-px.bot.cd/frontend/" },
        { text: "Linux 服务器", link: "https://java-px.bot.cd/linux/" },
        { text: "云原生 / Docker / K8s", link: "https://java-px.bot.cd/cloud-native/" },
        { text: "AI 工具 / 大模型", link: "https://java-px.bot.cd/ai/" },
        { text: "大数据", link: "https://java-px.bot.cd/bigdata/" },
        { text: "计算机网络", link: "https://java-px.bot.cd/network/" },
        { text: "视频处理", link: "https://java-px.bot.cd/video/" },
        { text: "文件系统与存储", link: "https://java-px.bot.cd/filesystem/" },
        { text: "Java 语言", link: "https://java-px.bot.cd/java-language/" },
        { text: "系统设计", link: "https://java-px.bot.cd/system-design/" },
        { text: "PostgreSQL", link: "https://java-px.bot.cd/postgresql/" },
        { text: "可观测性", link: "https://java-px.bot.cd/observability/" },
        { text: "安全", link: "https://java-px.bot.cd/security/" },
        { text: "DevOps", link: "https://java-px.bot.cd/devops/" },
        { text: "Rust", link: "https://java-px.bot.cd/rust/" },
        { text: "Go", link: "https://java-px.bot.cd/go/" },
        { text: "ClickHouse", link: "https://java-px.bot.cd/clickhouse/" },
        { text: "设计模式", link: "https://java-px.bot.cd/design-pattern/" },
        { text: "混沌工程", link: "https://java-px.bot.cd/chaos/" },
        { text: "物联网", link: "https://java-px.bot.cd/iot/" },
        { text: "安卓", link: "https://java-px.bot.cd/android/" },
        { text: "游戏开发", link: "https://java-px.bot.cd/game/" },
        ]
      }
    ],

    // === 各站独立 sidebar（render-config.py 保留原值）===
    sidebar: {
    
        
            
                
                    
                        
                            
                                
                                                                      '/': [
                                                                        {text:'🎯 开始',items:[{text:'📖 学习路径',link:'/path'}]},
                                                                        {text:'🧠 并发理论',items:[{text:'JMM 内存模型',link:'/01-concurrency-theory/jmm'},{text:'happens-before',link:'/01-concurrency-theory/happens-before'},{text:'CAS / Lock-Free',link:'/01-concurrency-theory/cas'},{text:'volatile / final',link:'/01-concurrency-theory/volatile'}]},
                                                                        {text:'🧵 线程池',items:[{text:'ThreadPoolExecutor',link:'/02-thread-pool/executor'},{text:'ForkJoinPool',link:'/02-thread-pool/forkjoin'},{text:'JDK 21 虚拟线程',link:'/02-thread-pool/virtual'}]},
                                                                        {text:'🏛️ 高可用理论',items:[{text:'CAP 定理',link:'/03-ha-theory/cap'},{text:'BASE / 最终一致性',link:'/03-ha-theory/base'},{text:'Raft 共识',link:'/03-ha-theory/raft'},{text:'Quorum 多数派',link:'/03-ha-theory/quorum'},{text:'幂等性设计',link:'/03-ha-theory/idempotency'}]},
                                                                        {text:'🚦 限流',items:[{text:'令牌桶算法',link:'/04-rate-limit/token-bucket'},{text:'漏桶 / 滑动窗口',link:'/04-rate-limit/leaky-bucket'},{text:'分布式限流',link:'/04-rate-limit/distributed'}]},
                                                                        {text:'⚡ 熔断降级',items:[{text:'熔断器三态',link:'/05-circuit-breaker/states'},{text:'Sentinel / Hystrix',link:'/05-circuit-breaker/impl'},{text:'Fallback 设计',link:'/05-circuit-breaker/fallback'}]},
                                                                        {text:'🧩 微服务',items:[{text:'服务拆分原则',link:'/06-microservice/split'},{text:'服务发现',link:'/06-microservice/discovery'},{text:'API 网关',link:'/06-microservice/gateway'},{text:'配置中心',link:'/06-microservice/config'}]},
                                                                        {text:'🔄 分布式事务',items:[{text:'2PC / 3PC',link:'/07-distributed-tx/2pc'},{text:'TCC 模式',link:'/07-distributed-tx/tcc'},{text:'Saga 模式',link:'/07-distributed-tx/saga'},{text:'本地消息表',link:'/07-distributed-tx/local-table'}]},
                                                                        {text:'📨 消息队列',items:[{text:'Kafka vs RabbitMQ',link:'/08-message-queue/compare'},{text:'顺序 / 幂等',link:'/08-message-queue/idempotency'},{text:'死信 / 重试',link:'/08-message-queue/dlq'}]},
                                                                        {text:'💾 缓存',items:[{text:'多级缓存架构',link:'/09-cache/architecture'},{text:'缓存三大问题',link:'/09-cache/breakdown'},{text:'一致性策略',link:'/09-cache/consistency'}]},
                                                                        {text:'🗄️ 分库分表',items:[{text:'水平 / 垂直拆分',link:'/10-database-sharding/strategy'},{text:'路由 / 扩容',link:'/10-database-sharding/routing'},{text:'分布式 ID',link:'/10-database-sharding/id'}]},
                                                                        {text:'🧠 DDD',items:[{text:'聚合 / 实体 / 值对象',link:'/11-ddd/basics'},{text:'限界上下文',link:'/11-ddd/bounded-context'},{text:'事件风暴',link:'/11-ddd/event-storming'}]},
                                                                        {text:'🧱 微服务模式',items:[{text:'Service Mesh',link:'/12-microservice-patterns/service-mesh'},{text:'Sidecar',link:'/12-microservice-patterns/sidecar'},{text:'Saga / Bulkhead',link:'/12-microservice-patterns/saga'}]},
                                                                        {text:'🔭 可观测',items:[{text:'Metrics / Tracing / Logging',link:'/13-observability/three-pillars'},{text:'OpenTelemetry',link:'/13-observability/otel'}]},
                                                                        {text:'🏢 企业案例',items:[{text:'秒杀系统',link:'/14-enterprise-cases/flash-sale'},{text:'短链系统',link:'/14-enterprise-cases/short-url'},{text:'异地多活',link:'/14-enterprise-cases/multi-region'}]}
                                                                      ]
    },

    socialLinks: [{icon:'github',link:'https://github.com'}],

    outline: { level: [2, 3], label: '页面大纲' },
    docFooter: { prev: '上一篇', next: '下一篇' },
    search: { provider: 'local' },

    footer: {
      message: '企业级架构 - 高可用 / 高并发 / 微服务 / DDD · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>',
      copyright: 'MIT License'
    },
  }
}))
