/**
 * @generated from shared-assets/vitepress-template/config.mts.tpl
 * DO NOT EDIT THIS FILE DIRECTLY — edit the template and re-run render-config.py
 *
 * 模板变量（render-config.py 替换）：
 *   iot         e.g. "ai", "java", "clickhouse"
 *   /iot/       e.g. "/ai/", "/clickhouse/"
 *   IoT      e.g. "AI 工程全栈"
 *   物联网 IoT 全栈知识图谱 - 通信协议 / 边缘计算 / 设备管理 / 时序数据 / 云平台 / 行业落地 · MQTT · CoAP · LoRaWAN · TDengine · 6 大类 · 93 节点       e.g. "系统化学习 AI 工具..."
 *   #0891b2     e.g. "#8b5cf6"
 *   zh-CN       e.g. "zh-CN"
 *   物联网 IoT 全栈知识图谱 - MQTT / CoAP / 边缘计算 / 时序数据 · 📚 <a href="https://java-px.bot.cd/iot/" target="_blank">iot 站主页</a> · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>  e.g. "AI 工程全栈 - 工具 / 大模型 / SDK / Agent"
 *   []   e.g. '[{ icon: "github", link: "https://github.com" }]'
 */
import { defineConfig } from 'vitepress'
import { withMermaid } from 'vitepress-plugin-mermaid'
import { fileURLToPath, URL } from 'node:url'

// P0: VitePress/rollup 默认 fs.allow 限制 cwd 外 import。用 vite alias 解决相对路径。
const SHARED_ASSETS = fileURLToPath(new URL('../../shared-assets', import.meta.url))

// P0: shared-assets/ 下的 .vue 组件 import vue 时需要显式 alias 指向本站点 node_modules。
// 否则 rollup 在 SHARED_ASSETS 目录找不到 vue，会报 "Rollup failed to resolve import 'vue'"。
// §8.81 QrShare 落地后暴露此问题。
// §8.81 二次修复：alias 还要覆盖 vue 子路径（vue/server-renderer · vue/compiler-sfc 等）
// 否则 vitepress SSR 阶段 import 'vue/server-renderer' 仍会 resolve 失败。
const VUE_DIR = fileURLToPath(new URL('../node_modules/vue/', import.meta.url))

// C11: Mermaid 跨站共享配置（inline 而非 import，避免 vite alias 在 Node 加载 config.mts 阶段不生效的问题）
// 同步源：shared-assets/mermaid-config/base.ts（修改时请同步更新此处）
// 见 §8.46
const mermaidBase = {
  securityLevel: 'loose',
  startOnLoad: false,
  theme: 'base',
  fontFamily: '"Inter", "PingFang SC", "Microsoft YaHei", system-ui, -apple-system, sans-serif',
} as const

function lightenHex(hex: string, ratio: number): string {
  const m = hex.replace('#', '').match(/^([0-9a-f]{6})$/i)
  if (!m) return hex
  const r = parseInt(m[1].slice(0, 2), 16)
  const g = parseInt(m[1].slice(2, 4), 16)
  const b = parseInt(m[1].slice(4, 6), 16)
  const mix = (c: number) => Math.round(c + (255 - c) * ratio)
  return '#' + [mix(r), mix(g), mix(b)].map(c => c.toString(16).padStart(2, '0')).join('')
}

function mermaidTheme(brand: string) {
  const soft = lightenHex(brand, 0.85)
  const ink = '#1f2937'
  const line = '#94a3b8'
  return {
    primaryColor: brand,
    primaryTextColor: ink,
    primaryBorderColor: brand,
    lineColor: line,
    secondaryColor: soft,
    tertiaryColor: '#fafafa',
    fontFamily: mermaidBase.fontFamily,
    fontSize: '14px',
  }
}

export default withMermaid( defineConfig({
  vite: {
    resolve: {
      alias: [
        { find: '@shared', replacement: SHARED_ASSETS },
        { find: /^vue(\/.*)?$/, replacement: `${VUE_DIR}$1` },
      ],
    },
    // §8.72：shared-assets/svg/ 共享 SVG 资产（CAP / Saga / 一致性 hash 等）
    // 只把 svg/ 子目录作为 public（避免泄漏 mermaid-config / glossary / template 等）
    publicDir: fileURLToPath(new URL('../../shared-assets/svg', import.meta.url)),
  },
    mermaid: {
    ...mermaidBase,
    themeVariables: mermaidTheme('#0891b2'),
  },
    base: '/iot/',
  title: 'IoT',
  description: '物联网 IoT 全栈知识图谱 - 通信协议 / 边缘计算 / 设备管理 / 时序数据 / 云平台 / 行业落地 · MQTT · CoAP · LoRaWAN · TDengine · 6 大类 · 93 节点',
  lang: 'zh-CN',
  lastUpdated: true,
  srcDir: 'docs',
  cleanUrls: true,
  ignoreDeadLinks: true,
  head: [
    ['meta', { name: 'viewport', content: 'width=device-width,initial-scale=1,viewport-fit=cover' }],
    ['meta', { name: 'theme-color', content: '#0891b2' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:locale', content: 'zh_CN' }],
    ['meta', { property: 'og:site_name', content: 'IoT' }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['link', { rel: 'icon', href: '/favicon.svg', type: 'image/svg+xml' }],
    ['link', { rel: 'icon', href: '/favicon.ico', type: 'image/x-icon' }],
    ['link', { rel: 'apple-touch-icon', href: '/apple-touch-icon.png', sizes: '180x180' }],
  ],
  themeConfig: {
    siteTitle: 'IoT',

    // === 统一 nav（C1 规范：顶部 7 项 + 跨站 dropdown）===
    // 1) 门户  2) 首页  3) 知识图谱  4) 思维导图  5) 命令速查  6) 学习路径  7) 更多站点 ▼
    nav: [
      { text: '🏠 门户', link: 'https://java-px.bot.cd/', target: '_blank' },
      { text: '首页', link: '/' },
      { text: '知识图谱', link: '/graph' },
      { text: '思维导图', link: '/mindmap' },
      { text: '命令速查', link: '/cheatsheet' },
      { text: '学习路径', link: '/path' },
      {
        text: '更多站点',
        items: [
                  { text: "ElasticSearch", link: "https://java-px.bot.cd/es/" },
        { text: "MySQL", link: "https://java-px.bot.cd/mysql/" },
        { text: "Redis", link: "https://java-px.bot.cd/redis/" },
        { text: "微服务 / Spring Cloud", link: "https://java-px.bot.cd/cloud/" },
        { text: "Python", link: "https://java-px.bot.cd/python/" },
        { text: "Kafka", link: "https://java-px.bot.cd/kafka/" },
        { text: "Java Web 开发", link: "https://java-px.bot.cd/java/" },
        { text: "在线工具", link: "https://java-px.bot.cd/tools/" },
        { text: "前端 & Node", link: "https://java-px.bot.cd/frontend/" },
        { text: "Linux 服务器", link: "https://java-px.bot.cd/linux/" },
        { text: "云原生 / Docker / K8s", link: "https://java-px.bot.cd/cloud-native/" },
        { text: "AI 工具 / 大模型", link: "https://java-px.bot.cd/ai/" },
        { text: "大数据", link: "https://java-px.bot.cd/bigdata/" },
        { text: "计算机网络", link: "https://java-px.bot.cd/network/" },
        { text: "视频处理", link: "https://java-px.bot.cd/video/" },
        { text: "文件系统与存储", link: "https://java-px.bot.cd/filesystem/" },
        { text: "Java 语言", link: "https://java-px.bot.cd/java-language/" },
        { text: "企业级架构", link: "https://java-px.bot.cd/architecture/" },
        { text: "系统设计", link: "https://java-px.bot.cd/system-design/" },
        { text: "PostgreSQL", link: "https://java-px.bot.cd/postgresql/" },
        { text: "可观测性", link: "https://java-px.bot.cd/observability/" },
        { text: "安全", link: "https://java-px.bot.cd/security/" },
        { text: "DevOps", link: "https://java-px.bot.cd/devops/" },
        { text: "Rust", link: "https://java-px.bot.cd/rust/" },
        { text: "Go", link: "https://java-px.bot.cd/go/" },
        { text: "ClickHouse", link: "https://java-px.bot.cd/clickhouse/" },
        { text: "设计模式", link: "https://java-px.bot.cd/design-pattern/" },
        { text: "混沌工程", link: "https://java-px.bot.cd/chaos/" },
        { text: "安卓", link: "https://java-px.bot.cd/android/" },
        { text: "游戏开发", link: "https://java-px.bot.cd/game/" },
        ]
      }
    ],

    // === 各站独立 sidebar（render-config.py 保留原值）===
    sidebar: {
    
        
            
                
                    
                        
                            
                                                              '/': [
                                                                {
                                                                  text: '📡 物联网总览',
                                                                  collapsed: false,
                                                                  items: [
                                                                    { text: '首页', link: '/' },
                                                                    { text: '知识图谱位置', link: '/README' },
                                                                  ]
                                                                },
                                                                {
                                                                  text: '🗺️ 结构图',
                                                                  collapsed: false,
                                                                  items: [
                                                                    { text: '思维导图', link: '/mindmap' },
                                                                  ]
                                                                },
                                                                {
                                                                  text: '📡 通信协议',
                                                                  collapsed: false,
                                                                  items: [
                                                                    { text: '章节目录', link: '/01-protocol/' },
                                                                    { text: 'MQTT 5.0', link: '/01-protocol/mqtt' },
                                                                    { text: 'CoAP', link: '/01-protocol/coap' },
                                                                    { text: 'Modbus / OPC-UA', link: '/01-protocol/modbus' },
                                                                    { text: 'LoRaWAN / NB-IoT', link: '/01-protocol/lpwan' },
                                                                  ]
                                                                },
                                                                {
                                                                  text: '🔌 设备与硬件',
                                                                  collapsed: false,
                                                                  items: [
                                                                    { text: '章节目录', link: '/02-device/' },
                                                                    { text: 'MCU / SoC', link: '/02-device/mcu' },
                                                                    { text: 'FreeRTOS / Zephyr', link: '/02-device/rtos' },
                                                                    { text: '传感器', link: '/02-device/sensor' },
                                                                    { text: '网关硬件', link: '/02-device/gateway' },
                                                                  ]
                                                                },
                                                                {
                                                                  text: '🌐 边缘计算',
                                                                  collapsed: false,
                                                                  items: [
                                                                    { text: '章节目录', link: '/03-edge/' },
                                                                    { text: 'EdgeX / KubeEdge', link: '/03-edge/framework' },
                                                                    { text: '边缘智能 AI', link: '/03-edge/ai-edge' },
                                                                    { text: '离线自治', link: '/03-edge/offline' },
                                                                    { text: 'K8s 边缘', link: '/03-edge/k8s-edge' },
                                                                  ]
                                                                },
                                                                {
                                                                  text: '⚙️ 设备管理',
                                                                  collapsed: false,
                                                                  items: [
                                                                    { text: '章节目录', link: '/04-management/' },
                                                                    { text: '设备影子 / 物模型', link: '/04-management/shadow' },
                                                                    { text: '固件 OTA', link: '/04-management/ota' },
                                                                    { text: '设备安全', link: '/04-management/security' },
                                                                  ]
                                                                },
                                                                {
                                                                  text: '📊 时序数据',
                                                                  collapsed: false,
                                                                  items: [
                                                                    { text: '章节目录', link: '/05-timeseries/' },
                                                                    { text: '时序库选型', link: '/05-timeseries/database' },
                                                                    { text: '流处理 / Downsampling', link: '/05-timeseries/processing' },
                                                                    { text: 'Grafana / Kafka', link: '/05-timeseries/integration' },
                                                                    { text: '数据模型', link: '/05-timeseries/schema' },
                                                                  ]
                                                                },
                                                                {
                                                                  text: '☁️ 云平台与行业',
                                                                  collapsed: false,
                                                                  items: [
                                                                    { text: '章节目录', link: '/06-platform/' },
                                                                    { text: '公有云 IoT', link: '/06-platform/public-cloud' },
                                                                    { text: '自建 IoT 平台', link: '/06-platform/self-hosted' },
                                                                    { text: '智能家居 Matter', link: '/06-platform/smart-home' },
                                                                    { text: '工业互联网 IIoT', link: '/06-platform/iiot' },
                                                                  ]
                                                                },
                                                                {
                                                                  text: '🚶 学习',
                                                                  collapsed: false,
                                                                  items: [
                                                                    { text: '学习路径', link: '/path' },
                                                                    { text: '常见问题', link: '/questions' },
                                                                    { text: '速查表', link: '/cheatsheet' },
                                                                  ]
                                                                }
                                                              ]
    },

    socialLinks: [],

    outline: { level: [2, 3], label: '页面大纲' },
    docFooter: { prev: '上一篇', next: '下一篇' },
    search: { provider: 'local' },

    footer: {
      message: '物联网 IoT 全栈知识图谱 - MQTT / CoAP / 边缘计算 / 时序数据 · 📚 <a href="https://java-px.bot.cd/iot/" target="_blank">iot 站主页</a> · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>',
      copyright: 'MIT License'
    },
  }
}))
