/**
 * @generated from shared-assets/vitepress-template/config.mts.tpl
 * DO NOT EDIT THIS FILE DIRECTLY — edit the template and re-run render-config.py
 *
 * 模板变量（render-config.py 替换）：
 *   rust         e.g. "ai", "java", "clickhouse"
 *   /rust/       e.g. "/ai/", "/clickhouse/"
 *   Rust      e.g. "AI 工程全栈"
 *   系统编程与高性能服务深度图谱 - 所有权 / 借用 / 生命周期 · 类型系统 / Trait · Cargo / crates.io · async-await / Tokio · unsafe / FFI / WASM · 6 大类 · 35 节点       e.g. "系统化学习 AI 工具..."
 *   #ce422b     e.g. "#8b5cf6"
 *   zh-CN       e.g. "zh-CN"
 *   本站点基于 VitePress 构建 · CC BY-NC-SA 4.0 · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>  e.g. "AI 工程全栈 - 工具 / 大模型 / SDK / Agent"
 *   []   e.g. '[{ icon: "github", link: "https://github.com" }]'
 */
import { defineConfig } from 'vitepress'
import { fileURLToPath, URL } from 'node:url'

// P0: VitePress/rollup 默认 fs.allow 限制 cwd 外 import。用 vite alias 解决相对路径。
const SHARED_ASSETS = fileURLToPath(new URL('../../shared-assets', import.meta.url))

export default defineConfig({
  vite: {
    resolve: {
      alias: [
        { find: '@shared', replacement: SHARED_ASSETS },
      ],
    },
  },
  base: '/rust/',
  title: 'Rust',
  description: '系统编程与高性能服务深度图谱 - 所有权 / 借用 / 生命周期 · 类型系统 / Trait · Cargo / crates.io · async-await / Tokio · unsafe / FFI / WASM · 6 大类 · 35 节点',
  lang: 'zh-CN',
  lastUpdated: true,
  srcDir: 'docs',
  cleanUrls: true,
  ignoreDeadLinks: true,
  head: [
    ['meta', { name: 'viewport', content: 'width=device-width,initial-scale=1,viewport-fit=cover' }],
    ['meta', { name: 'theme-color', content: '#ce422b' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:locale', content: 'zh_CN' }],
    ['meta', { property: 'og:site_name', content: 'Rust' }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['link', { rel: 'icon', href: '/favicon.svg', type: 'image/svg+xml' }],
    ['link', { rel: 'icon', href: '/favicon.ico', type: 'image/x-icon' }],
    ['link', { rel: 'apple-touch-icon', href: '/apple-touch-icon.png', sizes: '180x180' }],
  ],
  themeConfig: {
    siteTitle: 'Rust',

    // === 统一 nav（C1 规范：顶部 7 项 + 跨站 dropdown）===
    // 1) 门户  2) 首页  3) 知识图谱  4) 思维导图  5) 命令速查  6) 学习路径  7) 更多站点 ▼
    nav: [
      { text: '🏠 门户', link: 'https://java-px.bot.cd/', target: '_blank' },
      { text: '首页', link: '/' },
      { text: '知识图谱', link: '/graph' },
      { text: '思维导图', link: '/mindmap' },
      { text: '命令速查', link: '/cheatsheet' },
      { text: '学习路径', link: '/path' },
      {
        text: '更多站点',
        items: [
                  { text: "ElasticSearch", link: "https://java-px.bot.cd/es/" },
        { text: "MySQL", link: "https://java-px.bot.cd/mysql/" },
        { text: "Redis", link: "https://java-px.bot.cd/redis/" },
        { text: "微服务 / Spring Cloud", link: "https://java-px.bot.cd/cloud/" },
        { text: "Python", link: "https://java-px.bot.cd/python/" },
        { text: "Kafka", link: "https://java-px.bot.cd/kafka/" },
        { text: "Java Web 开发", link: "https://java-px.bot.cd/java/" },
        { text: "在线工具", link: "https://java-px.bot.cd/tools/" },
        { text: "前端 & Node", link: "https://java-px.bot.cd/frontend/" },
        { text: "Linux 服务器", link: "https://java-px.bot.cd/linux/" },
        { text: "云原生 / Docker / K8s", link: "https://java-px.bot.cd/cloud-native/" },
        { text: "AI 工具 / 大模型", link: "https://java-px.bot.cd/ai/" },
        { text: "大数据", link: "https://java-px.bot.cd/bigdata/" },
        { text: "计算机网络", link: "https://java-px.bot.cd/network/" },
        { text: "视频处理", link: "https://java-px.bot.cd/video/" },
        { text: "文件系统与存储", link: "https://java-px.bot.cd/filesystem/" },
        { text: "Java 语言", link: "https://java-px.bot.cd/java-language/" },
        { text: "企业级架构", link: "https://java-px.bot.cd/architecture/" },
        { text: "系统设计", link: "https://java-px.bot.cd/system-design/" },
        { text: "PostgreSQL", link: "https://java-px.bot.cd/postgresql/" },
        { text: "可观测性", link: "https://java-px.bot.cd/observability/" },
        { text: "安全", link: "https://java-px.bot.cd/security/" },
        { text: "DevOps", link: "https://java-px.bot.cd/devops/" },
        { text: "Go", link: "https://java-px.bot.cd/go/" },
        { text: "ClickHouse", link: "https://java-px.bot.cd/clickhouse/" },
        { text: "设计模式", link: "https://java-px.bot.cd/design-pattern/" },
        { text: "混沌工程", link: "https://java-px.bot.cd/chaos/" },
        { text: "物联网", link: "https://java-px.bot.cd/iot/" },
        { text: "安卓", link: "https://java-px.bot.cd/android/" },
        { text: "游戏开发", link: "https://java-px.bot.cd/game/" },
        ]
      }
    ],

    // === 各站独立 sidebar（render-config.py 保留原值）===
    sidebar: {
    
        
            
                              '/': [
                                {
                                  text: '🦀 Rust 基础', collapsed: false, items: [
                                    { text: 'Rust 总览', link: '/01-basics/overview' },
                                    { text: '所有权 Ownership', link: '/01-basics/ownership' },
                                    { text: '借用 Borrowing', link: '/01-basics/borrowing' },
                                    { text: '生命周期 Lifetimes', link: '/01-basics/lifetimes' },
                                    { text: '语法基础', link: '/01-basics/syntax-fundamentals' },
                                    { text: 'Hello World 实战', link: '/01-basics/hello-world' }
                                  ]
                                },
                                {
                                  text: '🏷️ 类型系统与 Trait', collapsed: false, items: [
                                    { text: '类型系统总览', link: '/02-types-traits/overview' },
                                    { text: '枚举与模式匹配', link: '/02-types-traits/enum-and-pattern' },
                                    { text: '泛型 Generics', link: '/02-types-traits/generics' },
                                    { text: 'Trait', link: '/02-types-traits/trait' },
                                    { text: '高级类型', link: '/02-types-traits/advanced-types' },
                                    { text: 'Trait 对象与动态分发', link: '/02-types-traits/trait-objects' }
                                  ]
                                },
                                {
                                  text: '📦 生态与工具链', collapsed: false, items: [
                                    { text: '生态总览', link: '/03-ecosystem/overview' },
                                    { text: 'Cargo', link: '/03-ecosystem/cargo' },
                                    { text: 'crates.io', link: '/03-ecosystem/crates-io' },
                                    { text: '标准库', link: '/03-ecosystem/std-lib' },
                                    { text: '测试与工具链', link: '/03-ecosystem/tooling' }
                                  ]
                                },
                                {
                                  text: '⚡ 并发与异步', collapsed: false, items: [
                                    { text: '并发总览', link: '/04-concurrency/overview' },
                                    { text: '线程与 Thread', link: '/04-concurrency/threads' },
                                    { text: 'async / await', link: '/04-concurrency/async-await' },
                                    { text: 'Tokio 运行时', link: '/04-concurrency/tokio' },
                                    { text: 'Channel 与共享状态', link: '/04-concurrency/channels' }
                                  ]
                                },
                                {
                                  text: '⚙️ 系统编程', collapsed: false, items: [
                                    { text: '系统编程总览', link: '/05-systems/overview' },
                                    { text: 'unsafe Rust', link: '/05-systems/unsafe' },
                                    { text: 'FFI 与 C 互操作', link: '/05-systems/ffi' },
                                    { text: '嵌入式 Rust', link: '/05-systems/embedded' },
                                    { text: 'WebAssembly', link: '/05-systems/wasm' },
                                    { text: '性能优化', link: '/05-systems/performance' }
                                  ]
                                },
                                {
                                  text: '🚀 进阶与实战', collapsed: false, items: [
                                    { text: '宏 Macro', link: '/06-advanced/macro' },
                                    { text: '闭包与迭代器', link: '/06-advanced/closure-and-iterator' },
                                    { text: '智能指针', link: '/06-advanced/smart-pointer' },
                                    { text: '错误处理', link: '/06-advanced/error-handling' },
                                    { text: '异步生态对比', link: '/06-advanced/async-ecosystem' },
                                    { text: '案例研究', link: '/06-advanced/case-study' }
                                  ]
                                }
                              ]
    },

    socialLinks: [],

    outline: { level: [2, 3], label: '页面大纲' },
    docFooter: { prev: '上一篇', next: '下一篇' },
    search: { provider: 'local' },

    footer: {
      message: '本站点基于 VitePress 构建 · CC BY-NC-SA 4.0 · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>',
      copyright: 'MIT License'
    },
  }
})
