/**
 * @generated from shared-assets/vitepress-template/config.mts.tpl
 * DO NOT EDIT THIS FILE DIRECTLY — edit the template and re-run render-config.py
 *
 * 模板变量（render-config.py 替换）：
 *   chaos         e.g. "ai", "java", "clickhouse"
 *   /chaos/       e.g. "/ai/", "/clickhouse/"
 *   混沌工程      e.g. "AI 工程全栈"
 *   Chaos Engineering：原则、工具（Chaos Mesh / Litmus / Gremlin / ChaosBlade）、韧性模式与游戏日       e.g. "系统化学习 AI 工具..."
 *   #e11d48     e.g. "#8b5cf6"
 *   zh-CN       e.g. "zh-CN"
 *   基于 VitePress 构建 · 混沌工程 28 站知识图谱 · · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>  e.g. "AI 工程全栈 - 工具 / 大模型 / SDK / Agent"
 *   [
      { icon: 'github', link: 'https://github.com/chaos-mesh/chaos-mesh' },
    ]   e.g. '[{ icon: "github", link: "https://github.com" }]'
 */
import { defineConfig } from 'vitepress'
import { fileURLToPath, URL } from 'node:url'

// P0: VitePress/rollup 默认 fs.allow 限制 cwd 外 import。用 vite alias 解决相对路径。
const SHARED_ASSETS = fileURLToPath(new URL('../../shared-assets', import.meta.url))

// P0: shared-assets/ 下的 .vue 组件 import vue 时需要显式 alias 指向本站点 node_modules。
// 否则 rollup 在 SHARED_ASSETS 目录找不到 vue，会报 "Rollup failed to resolve import 'vue'"。
// §8.81 QrShare 落地后暴露此问题。
const VUE = fileURLToPath(new URL('../node_modules/vue', import.meta.url))

export default defineConfig({
  vite: {
    resolve: {
      alias: [
        { find: '@shared', replacement: SHARED_ASSETS },
        { find: /^vue$/, replacement: VUE },
      ],
    },
    // §8.72：shared-assets/svg/ 共享 SVG 资产（CAP / Saga / 一致性 hash 等）
    // 只把 svg/ 子目录作为 public（避免泄漏 mermaid-config / glossary / template 等）
    publicDir: fileURLToPath(new URL('../../shared-assets/svg', import.meta.url)),
  },
  base: '/chaos/',
  title: '混沌工程',
  description: 'Chaos Engineering：原则、工具（Chaos Mesh / Litmus / Gremlin / ChaosBlade）、韧性模式与游戏日',
  lang: 'zh-CN',
  lastUpdated: true,
  srcDir: 'docs',
  cleanUrls: true,
  ignoreDeadLinks: true,
  head: [
    ['meta', { name: 'viewport', content: 'width=device-width,initial-scale=1,viewport-fit=cover' }],
    ['meta', { name: 'theme-color', content: '#e11d48' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:locale', content: 'zh_CN' }],
    ['meta', { property: 'og:site_name', content: '混沌工程' }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['link', { rel: 'icon', href: '/favicon.svg', type: 'image/svg+xml' }],
    ['link', { rel: 'icon', href: '/favicon.ico', type: 'image/x-icon' }],
    ['link', { rel: 'apple-touch-icon', href: '/apple-touch-icon.png', sizes: '180x180' }],
  ],
  themeConfig: {
    siteTitle: '混沌工程',

    // === 统一 nav（C1 规范：顶部 7 项 + 跨站 dropdown）===
    // 1) 门户  2) 首页  3) 知识图谱  4) 思维导图  5) 命令速查  6) 学习路径  7) 更多站点 ▼
    nav: [
      { text: '🏠 门户', link: 'https://java-px.bot.cd/', target: '_blank' },
      { text: '首页', link: '/' },
      { text: '知识图谱', link: '/graph' },
      { text: '思维导图', link: '/mindmap' },
      { text: '命令速查', link: '/cheatsheet' },
      { text: '学习路径', link: '/path' },
      {
        text: '更多站点',
        items: [
                  { text: "ElasticSearch", link: "https://java-px.bot.cd/es/" },
        { text: "MySQL", link: "https://java-px.bot.cd/mysql/" },
        { text: "Redis", link: "https://java-px.bot.cd/redis/" },
        { text: "微服务 / Spring Cloud", link: "https://java-px.bot.cd/cloud/" },
        { text: "Python", link: "https://java-px.bot.cd/python/" },
        { text: "Kafka", link: "https://java-px.bot.cd/kafka/" },
        { text: "Java Web 开发", link: "https://java-px.bot.cd/java/" },
        { text: "在线工具", link: "https://java-px.bot.cd/tools/" },
        { text: "前端 & Node", link: "https://java-px.bot.cd/frontend/" },
        { text: "Linux 服务器", link: "https://java-px.bot.cd/linux/" },
        { text: "云原生 / Docker / K8s", link: "https://java-px.bot.cd/cloud-native/" },
        { text: "AI 工具 / 大模型", link: "https://java-px.bot.cd/ai/" },
        { text: "大数据", link: "https://java-px.bot.cd/bigdata/" },
        { text: "计算机网络", link: "https://java-px.bot.cd/network/" },
        { text: "视频处理", link: "https://java-px.bot.cd/video/" },
        { text: "文件系统与存储", link: "https://java-px.bot.cd/filesystem/" },
        { text: "Java 语言", link: "https://java-px.bot.cd/java-language/" },
        { text: "企业级架构", link: "https://java-px.bot.cd/architecture/" },
        { text: "系统设计", link: "https://java-px.bot.cd/system-design/" },
        { text: "PostgreSQL", link: "https://java-px.bot.cd/postgresql/" },
        { text: "可观测性", link: "https://java-px.bot.cd/observability/" },
        { text: "安全", link: "https://java-px.bot.cd/security/" },
        { text: "DevOps", link: "https://java-px.bot.cd/devops/" },
        { text: "Rust", link: "https://java-px.bot.cd/rust/" },
        { text: "Go", link: "https://java-px.bot.cd/go/" },
        { text: "ClickHouse", link: "https://java-px.bot.cd/clickhouse/" },
        { text: "设计模式", link: "https://java-px.bot.cd/design-pattern/" },
        { text: "物联网", link: "https://java-px.bot.cd/iot/" },
        { text: "安卓", link: "https://java-px.bot.cd/android/" },
        { text: "游戏开发", link: "https://java-px.bot.cd/game/" },
        ]
      }
    ],

    // === 各站独立 sidebar（render-config.py 保留原值）===
    sidebar: {
    
        
            
                
                    
                        
                            
                                
                                                                      '/01-foundations/': [
                                                                        { text: '基础篇', items: [
                                                                          { text: '概览', link: '/01-foundations/overview' },
                                                                          { text: '历史与哲学', link: '/01-foundations/history' },
                                                                          { text: '稳态假设', link: '/01-foundations/steady-state' },
                                                                          { text: '爆炸半径', link: '/01-foundations/blast-radius' },
                                                                        ]},
                                                                      ],
                                                                      '/02-chaos-mesh/': [
                                                                        { text: 'Chaos Mesh', items: [
                                                                          { text: '概览', link: '/02-chaos-mesh/overview' },
                                                                          { text: '架构与组件', link: '/02-chaos-mesh/architecture' },
                                                                          { text: 'PodChaos 实验', link: '/02-chaos-mesh/pod-chaos' },
                                                                          { text: 'NetworkChaos 实验', link: '/02-chaos-mesh/network-chaos' },
                                                                          { text: '工作流编排', link: '/02-chaos-mesh/workflow' },
                                                                        ]},
                                                                      ],
                                                                      '/03-litmus/': [
                                                                        { text: 'Litmus', items: [
                                                                          { text: '概览', link: '/03-litmus/overview' },
                                                                          { text: 'ChaosExperiment CRD', link: '/03-litmus/chaos-experiment' },
                                                                          { text: 'Probe 与 Check', link: '/03-litmus/probe-check' },
                                                                          { text: 'Litmus SDK', link: '/03-litmus/sdk' },
                                                                        ]},
                                                                      ],
                                                                      '/04-platform-compare/': [
                                                                        { text: '工具对比', items: [
                                                                          { text: '概览', link: '/04-platform-compare/overview' },
                                                                          { text: 'Chaos Mesh vs Litmus', link: '/04-platform-compare/mesh-vs-litmus' },
                                                                          { text: '开源 vs 商业 (Gremlin)', link: '/04-platform-compare/open-vs-commercial' },
                                                                          { text: '选型决策树', link: '/04-platform-compare/decision-tree' },
                                                                        ]},
                                                                      ],
                                                                      '/05-resilience-patterns/': [
                                                                        { text: '韧性模式', items: [
                                                                          { text: '概览', link: '/05-resilience-patterns/overview' },
                                                                          { text: '重试与退避', link: '/05-resilience-patterns/retry-backoff' },
                                                                          { text: '熔断器', link: '/05-resilience-patterns/circuit-breaker' },
                                                                          { text: '限流与降级', link: '/05-resilience-patterns/rate-limit-degrade' },
                                                                          { text: '舱壁与隔离', link: '/05-resilience-patterns/bulkhead' },
                                                                          { text: '多活与灾备', link: '/05-resilience-patterns/multi-region-dr' },
                                                                        ]},
                                                                      ],
                                                                      '/06-game-day/': [
                                                                        { text: '游戏日', items: [
                                                                          { text: '概览', link: '/06-game-day/overview' },
                                                                          { text: '演练设计', link: '/06-game-day/exercise-design' },
                                                                          { text: '角色分工', link: '/06-game-day/roles' },
                                                                          { text: '复盘与改进', link: '/06-game-day/retro' },
                                                                        ]},
                                                                      ],
                                                                      '/07-observability-for-chaos/': [
                                                                        { text: '混沌可观测性', items: [
                                                                          { text: '概览', link: '/07-observability-for-chaos/overview' },
                                                                          { text: '稳态假设度量', link: '/07-observability-for-chaos/measure-steady-state' },
                                                                          { text: 'SLO 反馈环', link: '/07-observability-for-chaos/slo-feedback-loop' },
                                                                          { text: '实战案例', link: '/07-observability-for-chaos/case-study' },
                                                                        ]},
                                                                      ]
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com/chaos-mesh/chaos-mesh' },
    ],

    outline: { level: [2, 3], label: '页面大纲' },
    docFooter: { prev: '上一篇', next: '下一篇' },
    search: { provider: 'local' },

    footer: {
      message: '基于 VitePress 构建 · 混沌工程 28 站知识图谱 · · 🏠 <a href="https://java-px.bot.cd/" target="_blank">门户首页</a>',
      copyright: 'MIT License'
    },
  }
})
