name: test runner pool
on: workflow_dispatch
jobs:
  test-ubuntu-22:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - run: echo "ubuntu-22.04 works at $(date)"
  test-ubuntu-latest:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - run: echo "ubuntu-latest works at $(date)"
  test-ubuntu-24:
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    steps:
      - run: echo "ubuntu-24.04 works at $(date)"
